import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { activateOrganization, assignOrganizationUser, createOrganization, deactivateOrganization, revokeImpactContribution, revokeOrganizationUser, verifyImpactParticipation, waiveImpactReciprocity } from '../actions';

export default async function AdminImpact() {
  const db = await createClient(); const { data: { user } } = await db.auth.getUser(); if (!user) redirect('/login'); const { data: me } = await db.from('profiles').select('role').eq('id', user.id).single(); if (me?.role !== 'admin') redirect('/');
  const [{ data: organizations }, { data: participations }, { data: due }, { data: contributions }] = await Promise.all([
    db.from('organizations').select('id,name,status,city').order('created_at', { ascending: false }), db.from('impact_participations').select('id,student_id,status').in('status', ['joined', 'overdue', 'disputed']).limit(30), db.from('impact_reciprocity_state').select('student_id,cycle_number').eq('status', 'give_back_due').limit(30), db.from('impact_contributions').select('id,student_id,verified_minutes,verified_at,revoked_at').is('revoked_at', null).order('verified_at', { ascending: false }).limit(30),
  ]);
  return <main className="shell max-w-4xl py-10"><h1 className="text-4xl font-black">Admin · Impact</h1><p className="mt-2 text-stone-600">Audited Impact operations only.</p><form action={createOrganization} className="card mt-6 flex flex-wrap gap-2"><input name="name" required placeholder="Organization"/><input name="city" placeholder="City"/><button className="btn">Create organization</button></form><h2 className="mt-8 text-2xl font-black">Organizations</h2>{organizations?.map((org: any) => <div className="card mt-3" key={org.id}><b>{org.name}</b> · {org.status}<div className="mt-3 flex flex-wrap gap-2">{org.status !== 'active' && <form action={activateOrganization}><input type="hidden" name="id" value={org.id}/><button className="btn">Activate</button></form>}{org.status === 'active' && <form action={deactivateOrganization} className="flex gap-2"><input type="hidden" name="id" value={org.id}/><input name="reason" required minLength={3} placeholder="Suspension reason"/><button className="btn alt">Suspend</button></form>}<form action={assignOrganizationUser} className="flex gap-2"><input type="hidden" name="organizationId" value={org.id}/><input name="userId" required placeholder="Operator UUID"/><button className="btn">Assign operator</button></form><form action={revokeOrganizationUser} className="flex gap-2"><input type="hidden" name="organizationId" value={org.id}/><input name="userId" required placeholder="Operator UUID"/><input name="reason" required minLength={3} placeholder="Revocation reason"/><button className="btn alt">Revoke</button></form></div></div>)}<h2 className="mt-8 text-2xl font-black">Participation review</h2>{participations?.map((p: any) => <form action={verifyImpactParticipation} className="card mt-3 flex flex-wrap gap-2" key={p.id}><span>#{p.id.slice(-6)} · {p.status}</span><input type="hidden" name="id" value={p.id}/><input name="reason" required minLength={3} placeholder="Admin verification reason"/><button className="btn">Verify</button></form>)}<h2 className="mt-8 text-2xl font-black">Verified contributions</h2>{contributions?.map((c: any) => <form action={revokeImpactContribution} className="card mt-3 flex flex-wrap gap-2" key={c.id}><span>#{c.id.slice(-6)} · {c.verified_minutes} min</span><input type="hidden" name="id" value={c.id}/><input name="reason" required minLength={3} placeholder="Revocation reason"/><button className="btn alt">Revoke contribution</button></form>)}<h2 className="mt-8 text-2xl font-black">Reciprocity due</h2>{due?.map((s: any) => <form action={waiveImpactReciprocity} className="card mt-3 flex flex-wrap gap-2" key={s.student_id}><span>Student #{s.student_id.slice(-6)} · cycle {s.cycle_number}</span><input type="hidden" name="studentId" value={s.student_id}/><input type="hidden" name="cycle" value={s.cycle_number}/><input name="reason" required minLength={3} placeholder="Waiver reason"/><button className="btn alt">Waive</button></form>)}</main>;
}
