-- Apply after 0001_cinste.sql. These are fictional marketplace records.
insert into public.universities(name,sort_order) values ('ASE București',1),('POLITEHNICA București',2),('Universitatea din București',3),('Carol Davila',4),('Other',99) on conflict(name) do nothing;
insert into public.categories(name,slug,icon_identifier,sort_order) values ('Food & Drink','food-drink','coffee',1),('Cinema','cinema','film',2),('Hair & Grooming','hair-grooming','scissors',3),('Beauty & Personal Care','beauty','sparkles',4),('Fitness & Sports','fitness','dumbbell',5),('Entertainment','entertainment','party-popper',6),('Activities','activities','map-pin',7),('Education','education','book-open',8),('Mobility','mobility','bike',9),('Other','other','sparkles',99) on conflict(slug) do nothing;
insert into public.partners(name,slug,description,address,city,active) values ('Cafeneaua Verde','cafeneaua-verde','O cafenea fictivă pentru studenți.','Str. Academiei 12','București',true),('Cinema Luna','cinema-luna','Un cinema fictiv de cartier.','Calea Victoriei 88','București',true),('Barber Club','barber-club','Un barber shop fictiv.','Str. Dorobanți 41','București',true) on conflict(slug) do nothing;
insert into public.offers(partner_id,category_id,name,description,giver_price_bani,fulfillment_type,redemption_instructions,booking_url) select p.id,c.id,'Cappuccino','O cafea bună, din partea cuiva.',1500,'instant','Arată codul CINSTE la bar.',null from public.partners p,public.categories c where p.slug='cafeneaua-verde' and c.slug='food-drink' and not exists(select 1 from public.offers where name='Cappuccino');
insert into public.offers(partner_id,category_id,name,description,giver_price_bani,fulfillment_type,redemption_instructions) select p.id,c.id,'Movie Ticket','Un bilet la o proiecție selectată.',3000,'scheduled_event','Prezintă QR-ul la intrare.' from public.partners p,public.categories c where p.slug='cinema-luna' and c.slug='cinema' and not exists(select 1 from public.offers where name='Movie Ticket');
insert into public.offers(partner_id,category_id,name,description,giver_price_bani,fulfillment_type,redemption_instructions,booking_url) select p.id,c.id,'Student Haircut','O tunsoare pentru studenți.',5500,'appointment_required','Programează-te telefonic și menționează CINSTE.','https://example.com/book' from public.partners p,public.categories c where p.slug='barber-club' and c.slug='hair-grooming' and not exists(select 1 from public.offers where name='Student Haircut');
update public.offers o set localization_key = case when p.slug='cafeneaua-verde' and c.slug='food-drink' and o.name='Cappuccino' then 'cappuccino' when p.slug='cinema-luna' and c.slug='cinema' and o.name='Movie Ticket' then 'movie_ticket' when p.slug='barber-club' and c.slug='hair-grooming' and o.name='Student Haircut' then 'student_haircut' end from public.partners p, public.categories c where o.partner_id=p.id and o.category_id=c.id and o.localization_key is null and ((p.slug='cafeneaua-verde' and c.slug='food-drink' and o.name='Cappuccino') or (p.slug='cinema-luna' and c.slug='cinema' and o.name='Movie Ticket') or (p.slug='barber-club' and c.slug='hair-grooming' and o.name='Student Haircut'));
insert into public.campaigns(offer_id,name,sponsor_type,sponsor_display_name,funding_source,quantity_total,quantity_available,starts_at,ends_at,claim_expiration_minutes,status) select id,'Cafea de la CINSTE','cinste','CINSTE','admin',10,10,now()-interval '1 hour',now()+interval '14 days',60,'active' from public.offers where name='Cappuccino' and not exists(select 1 from public.campaigns where name='Cafea de la CINSTE');
insert into public.campaigns(offer_id,name,sponsor_type,funding_source,quantity_total,quantity_available,starts_at,ends_at,event_starts_at,event_ends_at,status) select id,'Seara de film','company','admin',12,12,now()-interval '1 hour',now()+interval '7 days',now()+interval '2 days',now()+interval '2 days 3 hours','active' from public.offers where name='Movie Ticket' and not exists(select 1 from public.campaigns where name='Seara de film');
insert into public.campaigns(offer_id,name,sponsor_type,funding_source,quantity_total,quantity_available,starts_at,ends_at,status) select id,'Tuns din partea casei','partner','admin',4,4,now()-interval '1 hour',now()+interval '14 days','active' from public.offers where name='Student Haircut' and not exists(select 1 from public.campaigns where name='Tuns din partea casei');
insert into public.campaigns(offer_id,name,sponsor_type,funding_source,quantity_total,quantity_available,starts_at,ends_at,status) select id,'Campanie epuizată','cinste','admin',2,0,now()-interval '1 hour',now()+interval '2 days','active' from public.offers where name='Cappuccino' and not exists(select 1 from public.campaigns where name='Campanie epuizată');
insert into public.campaigns(offer_id,name,sponsor_type,funding_source,quantity_total,quantity_available,starts_at,ends_at,status) select id,'În curând','cinste','admin',5,5,now()+interval '7 days',now()+interval '21 days','active' from public.offers where name='Cappuccino' and not exists(select 1 from public.campaigns where name='În curând');
