import { useCallback, useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, EmptyState, Loading, Button } from '@/components/ui';
import { getMyGivingOutcomes, presentGivingOutcome } from '@/lib/giver-reads';
import { useAppLocale } from '@/i18n';
import type { GivingOutcome } from '@/lib/types';
import { color, space, type } from '@/design/tokens';

export default function MyGiving() {
  const { t, isRTL } = useAppLocale(); const [outcomes, setOutcomes] = useState<GivingOutcome[]>([]); const [busy, setBusy] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(async () => { setBusy(true); setError(false); try { setOutcomes(await getMyGivingOutcomes()); } catch { setError(true); } finally { setBusy(false); } }, []); useEffect(() => { void load(); }, [load]);
  return <ScrollView contentContainerStyle={[styles.page, isRTL && styles.rtl]}>{busy ? <Loading label={t('giver.loading')} /> : error ? <Card><Text style={[styles.heading, isRTL && styles.textRtl]}>{t('giver.errorTitle')}</Text><Text style={[styles.copy, isRTL && styles.textRtl]}>{t('giver.errorCopy')}</Text><Button label={t('common.retry')} variant="quiet" onPress={() => void load()} /></Card> : !outcomes.length ? <EmptyState title={t('giver.emptyOutcomes')} copy={t('giver.emptyOutcomesCopy')} /> : <View style={styles.stack}>{outcomes.map((outcome) => { const view = presentGivingOutcome(outcome); return <Card key={outcome.order_item_id} style={styles.outcomeCard}><Text style={[styles.funded, isRTL && styles.textRtl]}>{t(outcome.funded_quantity === 1 ? 'giver.fundedOne' : 'giver.fundedMany', { count: outcome.funded_quantity })}</Text><Text style={[styles.heading, isRTL && styles.textRtl]} numberOfLines={2}>{outcome.offer_title}</Text><Text style={[styles.state, isRTL && styles.textRtl]}>{t(`giver.outcome.${view.state}`)}</Text>{view.metrics ? <View style={[styles.metrics, isRTL && styles.rowRtl]}><Metric label={t('giver.reserved')} value={view.metrics.reserved} /><Metric label={t('giver.redeemed')} value={view.metrics.redeemed} />{view.metrics.recordedUnreserved !== null && <Metric label={t('giver.recordedAvailable')} value={view.metrics.recordedUnreserved} />}{view.metrics.availableNow !== null && <Metric label={t('giver.available')} value={view.metrics.availableNow} />}</View> : <Text style={[styles.copy, isRTL && styles.textRtl]}>{t(`giver.outcomeCopy.${view.state}`)}</Text>}</Card>; })}</View>}</ScrollView>;
}
function Metric({ label, value }: { label: string; value: number }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ page: { flexGrow: 1, padding: space.lg, paddingBottom: space.xxl, backgroundColor: color.canvas }, rtl: {}, textRtl: { textAlign: 'right', writingDirection: 'rtl' }, stack: { gap: space.sm }, outcomeCard: { padding: space.md }, funded: { ...type.caption, color: color.primary, marginBottom: space.xs }, heading: { ...type.cardTitle, color: color.ink, marginBottom: space.xs }, state: { ...type.caption, color: color.secondaryText, marginBottom: space.sm }, copy: { ...type.bodySmall, color: color.secondaryText }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: space.xs }, rowRtl: { flexDirection: 'row-reverse' }, metric: { minWidth: '46%', flexGrow: 1, padding: space.sm, borderRadius: 10, backgroundColor: color.canvas }, metricLabel: { ...type.caption, color: color.secondaryText }, metricValue: { ...type.cardTitle, color: color.ink } });
