'use server';
import { z } from 'zod';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import type { OperationalActionState } from '@/lib/operational-action';
import { getWebLocale } from '@/lib/i18n/server';
import { organizationCopy } from '@/lib/i18n/organization';

const id = z.string().uuid();
const opportunity = z.object({ organizationId: id, title: z.string().trim().min(2).max(200), description: z.string().trim().min(1), activityDetails: z.string().trim().min(3).max(4000), requirements: z.string().trim().max(2000).optional().or(z.literal('')), organizationProvides: z.string().trim().max(2000).optional().or(z.literal('')), coordinatorName: z.string().trim().max(200).optional().or(z.literal('')), coordinatorContact: z.string().trim().max(300).optional().or(z.literal('')), accessibilityInformation: z.string().trim().max(2000).optional().or(z.literal('')), participantContactFields: z.array(z.enum(['email'])).default([]), category: z.enum(['community', 'education', 'environment', 'animals', 'events', 'skills', 'other']), mode: z.enum(['scheduled', 'flexible_remote']), city: z.string().trim().max(120), startsAt: z.string().optional(), endsAt: z.string().optional(), dueAt: z.string().min(1), minutes: z.coerce.number().int().min(1).max(1440), capacity: z.coerce.number().int().min(1).max(100000) });
function parseOpportunity(form: FormData) { return opportunity.parse({ ...Object.fromEntries(form), participantContactFields: form.getAll('participantContactFields') }); }
async function db() { const client = await createClient(); const { data: { user } } = await client.auth.getUser(); if (!user) throw new Error('AUTH_REQUIRED'); return client; }
function iso(value?: string) { return value ? new Date(value).toISOString() : null; }
function refresh() { revalidatePath('/organization'); }
function operationalError(error: unknown, t: ReturnType<typeof organizationCopy>): OperationalActionState { const message = error instanceof Error ? error.message : ''; if (message.includes('SELF_VERIFICATION_FORBIDDEN')) return { ok: false, message: t.errorSelfVerification }; if (message.includes('OPPORTUNITY_NOT_FINISHED')) return { ok: false, message: t.errorNotFinished }; if (message.includes('OPPORTUNITY_EXPIRED_INCOMPLETE')) return { ok: false, message: t.errorExpired }; if (message.includes('PARTICIPATION_NOT_VERIFIABLE') || message.includes('PARTICIPATION_NOT_RESOLVABLE')) return { ok: false, message: t.errorNotEligible }; if (message.includes('DRAFT') || message.includes('published')) return { ok: false, message: t.errorDraftOnly }; if (message.includes('AUTH_REQUIRED')) return { ok: false, message: t.errorSessionExpired }; return { ok: false, message: t.errorAction }; }
async function action(work: () => Promise<void>, success: keyof ReturnType<typeof organizationCopy>): Promise<OperationalActionState> { const t = organizationCopy(await getWebLocale()); try { await work(); return { ok: true, message: t[success] }; } catch (error) { return operationalError(error, t); } }
export async function createOpportunity(_: OperationalActionState, form: FormData) { return action(async () => { const v = parseOpportunity(form); const client = await db(); const { error } = await client.rpc('organization_create_impact_opportunity', { p_organization_id: v.organizationId, p_title: v.title, p_description: v.description, p_category: v.category, p_mode: v.mode, p_city: v.city || null, p_starts_at: v.mode === 'scheduled' ? iso(v.startsAt) : null, p_ends_at: v.mode === 'scheduled' ? iso(v.endsAt) : null, p_due_at: iso(v.dueAt), p_expected_eligible_minutes: v.minutes, p_capacity: v.capacity, p_activity_details: v.activityDetails, p_requirements: v.requirements || null, p_organization_provides: v.organizationProvides || null, p_coordinator_name: v.coordinatorName || null, p_coordinator_contact: v.coordinatorContact || null, p_accessibility_information: v.accessibilityInformation || null, p_participant_contact_fields: v.participantContactFields }); if (error) throw new Error(error.message); }, 'draftSaved'); }
export async function updateOpportunity(_: OperationalActionState, form: FormData) { return action(async () => { const v = opportunity.extend({ id }).parse({ ...Object.fromEntries(form), participantContactFields: form.getAll('participantContactFields') }); const client = await db(); const { error } = await client.rpc('organization_update_impact_opportunity', { p_opportunity_id: v.id, p_title: v.title, p_description: v.description, p_category: v.category, p_mode: v.mode, p_city: v.city || null, p_starts_at: v.mode === 'scheduled' ? iso(v.startsAt) : null, p_ends_at: v.mode === 'scheduled' ? iso(v.endsAt) : null, p_due_at: iso(v.dueAt), p_expected_eligible_minutes: v.minutes, p_capacity: v.capacity, p_activity_details: v.activityDetails, p_requirements: v.requirements || null, p_organization_provides: v.organizationProvides || null, p_coordinator_name: v.coordinatorName || null, p_coordinator_contact: v.coordinatorContact || null, p_accessibility_information: v.accessibilityInformation || null, p_participant_contact_fields: v.participantContactFields }); if (error) throw new Error(error.message); }, 'changesSaved'); }
export async function submitOpportunity(_: OperationalActionState, form: FormData) { return action(async () => { const v = z.object({ id }).parse(Object.fromEntries(form)); const { error } = await (await db()).rpc('organization_submit_impact_opportunity', { p_opportunity_id: v.id }); if (error) throw new Error(error.message); }, 'draftSaved'); }
export async function cancelOpportunity(_: OperationalActionState, form: FormData) { return action(async () => { const v = z.object({ id, reason: z.string().trim().min(3).max(500) }).parse(Object.fromEntries(form)); const { error } = await (await db()).rpc('organization_cancel_impact_opportunity', { p_opportunity_id: v.id, p_reason: v.reason }); if (error) throw new Error(error.message); }, 'opportunityCancelled'); }
export async function verifyParticipation(_: OperationalActionState, form: FormData) { return action(async () => { const v = z.object({ id }).parse(Object.fromEntries(form)); const { error } = await (await db()).rpc('organization_verify_impact_participation', { p_participation_id: v.id }); if (error) throw new Error(error.message); }, 'completionVerified'); }
export async function markAttendance(_: OperationalActionState, form: FormData) { return action(async () => { const v = z.object({ id }).parse(Object.fromEntries(form)); const { error } = await (await db()).rpc('organization_mark_impact_attendance', { p_participation_id: v.id, p_attendance: 'attended', p_reason: null }); if (error) throw new Error(error.message); }, 'outcomeRecorded'); }
export async function resolveParticipation(_: OperationalActionState, form: FormData) { return action(async () => { const v = z.object({ id, outcome: z.enum(['no_show', 'excused']), reason: z.string().trim().min(3).max(500) }).parse(Object.fromEntries(form)); const { error } = await (await db()).rpc('organization_resolve_impact_participation', { p_participation_id: v.id, p_outcome: v.outcome, p_reason: v.reason }); if (error) throw new Error(error.message); }, 'outcomeRecorded'); }
export async function reportIncident(_: OperationalActionState, form: FormData) { return action(async () => { const v = z.object({ participationId: id, category: z.enum(['safety_concern', 'harassment', 'inappropriate_behavior', 'injury', 'organization_issue', 'student_issue', 'other']), severity: z.enum(['low', 'medium', 'serious']), description: z.string().trim().min(3).max(4000) }).parse(Object.fromEntries(form)); const { error } = await (await db()).rpc('report_impact_incident', { p_participation_id: v.participationId, p_category: v.category, p_severity: v.severity, p_description: v.description }); if (error) throw new Error(error.message); }, 'outcomeRecorded'); }
