import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { cancelOpportunity, createOpportunity, publishOpportunity, resolveParticipation, updateOpportunity, verifyParticipation } from './actions';

const localDate = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : '';
const categories = ['community', 'education', 'environment', 'animals', 'events', 'skills', 'other'];

export default async function Organization() {
  const db = await createClient(); const { data: { user } } = await db.auth.getUser(); if (!user) redirect('/login');
  const [{ data: organizations }, { data: opportunities }, { data: participations }] = await Promise.all([
    db.from('organizations').select('id,name,status'),
    db.from('impact_opportunities').select('id,organization_id,title,description,category,status,mode,city,starts_at,ends_at,due_at,expected_eligible_minutes,capacity').order('created_at', { ascending: false }),
    db.from('impact_participations').select('id,opportunity_id,student_id,status,joined_at').order('joined_at', { ascending: false }),
  ]);
  if (!organizations?.length) redirect('/?error=Organization access required');
  const org = organizations[0]; const own = opportunities?.filter((row) => row.organization_id === org.id) ?? []; const ownIds = new Set(own.map((row) => row.id)); const participants = participations?.filter((row) => ownIds.has(row.opportunity_id)) ?? [];
  return <main className="shell max-w-5xl py-10"><h1 className="text-4xl font-black">Impact · {org.name}</h1><p className="mt-2 text-stone-600">Only your organization’s operational records are available here.</p><section className="card mt-6"><h2 className="text-2xl font-black">Create opportunity</h2><OpportunityFields organizationId={org.id} action={createOpportunity}/></section><section className="mt-8"><h2 className="text-2xl font-black">Opportunities</h2>{own.map((item) => <div className="card mt-3" key={item.id}><b>{item.title}</b> · {item.status} · due {new Date(item.due_at).toLocaleString('ro-RO')}{item.status === 'draft' && <details className="mt-3"><summary className="cursor-pointer font-bold text-forest">Edit draft</summary><OpportunityFields organizationId={org.id} item={item} action={updateOpportunity}/></details>}<div className="mt-3 flex flex-wrap gap-2">{item.status === 'draft' && <form action={publishOpportunity}><input type="hidden" name="id" value={item.id}/><button className="btn">Publish</button></form>}{['draft', 'published'].includes(item.status) && <form action={cancelOpportunity} className="flex gap-2"><input type="hidden" name="id" value={item.id}/><input name="reason" required minLength={3} placeholder="Cancellation reason"/><button className="btn alt">Cancel</button></form>}</div></div>)}</section><section className="mt-8"><h2 className="text-2xl font-black">Participants</h2><p className="mt-1 text-sm text-stone-600">Only minimal operational identifiers are shown.</p>{participants.map((item) => <div className="card mt-3" key={item.id}><b>Student #{item.student_id.slice(-6)}</b> · {item.status}{item.status === 'joined' && <div className="mt-3 flex flex-wrap gap-2"><form action={verifyParticipation}><input type="hidden" name="id" value={item.id}/><button className="btn">Verify completion</button></form><form action={resolveParticipation} className="flex gap-2"><input type="hidden" name="id" value={item.id}/><input type="hidden" name="outcome" value="excused"/><input name="reason" required minLength={3} placeholder="Excusal reason"/><button className="btn alt">Excuse</button></form></div>}</div>)}</section></main>;
}

function OpportunityFields({ organizationId, item, action }: { organizationId: string; item?: any; action: (form: FormData) => void | Promise<void> }) { return <form action={action} className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="organizationId" value={organizationId}/>{item && <input type="hidden" name="id" value={item.id}/>}<input name="title" defaultValue={item?.title} placeholder="Title" required/><textarea name="description" defaultValue={item?.description} placeholder="Description" required className="md:col-span-2"/><select name="category" defaultValue={item?.category ?? 'community'}>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</select><select name="mode" defaultValue={item?.mode ?? 'flexible_remote'}><option value="flexible_remote">Flexible / remote</option><option value="scheduled">Scheduled</option></select><input name="city" defaultValue={item?.city ?? ''} placeholder="City"/><input name="dueAt" type="datetime-local" defaultValue={localDate(item?.due_at ?? null)} required/><input name="startsAt" type="datetime-local" defaultValue={localDate(item?.starts_at ?? null)}/><input name="endsAt" type="datetime-local" defaultValue={localDate(item?.ends_at ?? null)}/><input name="minutes" type="number" min="1" max="1440" defaultValue={item?.expected_eligible_minutes} placeholder="Eligible minutes" required/><input name="capacity" type="number" min="1" defaultValue={item?.capacity} placeholder="Capacity" required/><button className="btn md:col-span-2">{item ? 'Save draft changes' : 'Save draft'}</button></form>; }
