import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { selectAssignedOrganization } from '@/lib/organization-selection';
import { activeOrganizationWorkspaces } from '@/lib/organization-workspace';
import { groupOpportunities, participationAction, type OperatorOpportunity, type OperatorParticipation } from '@/lib/organization-operator';
import type { AppRole } from '@/lib/types';
import { OperationalForm, SubmitButton } from '@/components/operational-form';
import { cancelOpportunity, createOpportunity, publishOpportunity, resolveParticipation, updateOpportunity, verifyParticipation } from './actions';

const categories = ['community', 'education', 'environment', 'animals', 'events', 'skills', 'other'];
const labels: Record<string, string> = { draft: 'Draft', published: 'Published', cancelled: 'Cancelled', joined: 'Joined', completed: 'Completed', disputed: 'In Admin review', overdue: 'Overdue review', no_show: 'No show', excused: 'Excused', cancelled_by_organization: 'Cancelled by organization', late_cancelled: 'Late cancellation', expired_incomplete: 'Expired incomplete' };
const localDate = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : '';
const date = (value: string | null) => value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not recorded';
type Opportunity = OperatorOpportunity & { organization_id: string; title: string; description: string; category: string; city: string | null; expected_eligible_minutes: number; capacity: number };
type Participation = OperatorParticipation & { resolved_at: string | null; disputed_at: string | null };

export default async function Organization({ searchParams }: { searchParams: Promise<{ organizationId?: string }> }) {
  const db = await createClient(); const { data: { user } } = await db.auth.getUser(); if (!user) redirect('/login');
  const { data: profile } = await db.from('profiles').select('role').eq('id', user.id).maybeSingle();
  const organizations = await activeOrganizationWorkspaces(db, user.id, profile?.role as AppRole | undefined);
  if (!organizations.length) redirect('/?error=Organization access required');
  const org = selectAssignedOrganization(organizations, (await searchParams).organizationId); if (!org) redirect('/?error=Organization access required');
  const { data: opportunityRows, error: opportunitiesError } = await db.from('impact_opportunities').select('id,organization_id,title,description,category,status,mode,city,starts_at,ends_at,due_at,expected_eligible_minutes,capacity').eq('organization_id', org.id).order('created_at', { ascending: false });
  const opportunities = (opportunityRows ?? []) as Opportunity[]; const opportunityIds = opportunities.map((item) => item.id);
  const { data: participationRows, error: participationsError } = opportunityIds.length ? await db.from('impact_participations').select('id,opportunity_id,student_id,status,joined_at,resolved_at,disputed_at').in('opportunity_id', opportunityIds).order('joined_at', { ascending: false }) : { data: [] as Participation[], error: null };
  const participations = (participationRows ?? []) as Participation[]; const opportunityById = new Map(opportunities.map((item) => [item.id, item])); const grouped = groupOpportunities(opportunities);
  const queue = participations.filter((item) => { const opportunity = opportunityById.get(item.opportunity_id); return opportunity && ['resolve_scheduled', 'verify_flexible', 'admin_review'].includes(participationAction(item, opportunity)); });
  const inProgress = participations.filter((item) => { const opportunity = opportunityById.get(item.opportunity_id); return opportunity && participationAction(item, opportunity) === 'waiting_for_scheduled_end'; });
  const history = participations.filter((item) => !queue.some((queued) => queued.id === item.id) && !inProgress.some((active) => active.id === item.id));
  return <main className="shell operational-shell organization-v1-page py-10">
    <div className="page-heading organization-heading"><div><p className="eyebrow">Impact operations</p><h1>{org.name}</h1><p>Manage opportunities and participant outcomes for this organization only.</p></div><Badge value={org.status}/></div>
    {organizations.length > 1 && <form method="get" className="organization-selector"><label htmlFor="organizationId">Active organization</label><div><select id="organizationId" name="organizationId" defaultValue={org.id}>{organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="btn secondary">Switch organization</button></div></form>}
    <nav className="subnav" aria-label="Organization workspace"><a href="#action-queue">Action queue</a><a href="#opportunities">Opportunities</a><a href="#in-progress">In progress</a><a href="#participation-history">History &amp; review</a><a href="#create-opportunity">Create draft</a></nav>
    <section id="action-queue" className="section-block"><SectionHeading title="Action queue" description="Only records that can be acted on under the current server rules appear here."/>{opportunitiesError || participationsError ? <WorkspaceError /> : queue.length ? <div className="stack">{queue.map((item) => <ParticipationCard key={item.id} item={item} opportunity={opportunityById.get(item.opportunity_id)!}/>)}</div> : <Empty text="Nothing needs an operator action right now. Review and historical records remain below."/>}</section>
    <section id="opportunities" className="section-block"><SectionHeading title="Opportunities" description="Drafts, live work, and historical records are separated so the next step is clear."/>{opportunitiesError ? <WorkspaceError /> : <div className="opportunity-sections"><OpportunityGroup title="Drafts" description="Review details before publishing." items={grouped.drafts as Opportunity[]} participants={participations}/><OpportunityGroup title="Published" description="Current opportunities that students may be able to join." items={grouped.current as Opportunity[]} participants={participations}/><OpportunityGroup title="Past published" description="Past work remains available for participation history and review." items={grouped.past as Opportunity[]} participants={participations}/><OpportunityGroup title="Cancelled" description="Cancelled opportunities are retained as history." items={grouped.cancelled as Opportunity[]} participants={participations}/>{!opportunities.length && <Empty text="No opportunities yet. Create a draft to start planning a contribution activity."/>}</div>}</section>
    <section id="in-progress" className="section-block"><SectionHeading title="In progress" description="Scheduled work remains active until its end time. Operator resolution is not available before then."/>{participationsError ? <WorkspaceError /> : inProgress.length ? <div className="stack">{inProgress.map((item) => <ParticipationCard key={item.id} item={item} opportunity={opportunityById.get(item.opportunity_id)!}/>)}</div> : <Empty text="No scheduled participations are currently in progress."/>}</section>
    <section id="participation-history" className="section-block"><SectionHeading title="History &amp; review" description="Completed and resolved records stay separate from work requiring action. Overdue and disputed records require CINSTE Admin review."/>{participationsError ? <WorkspaceError /> : history.length ? <div className="stack">{history.map((item) => <ParticipationCard key={item.id} item={item} opportunity={opportunityById.get(item.opportunity_id)!}/>)}</div> : <Empty text="There is no resolved participation history for this organization yet."/>}</section>
    <section id="create-opportunity" className="section-block card form-card"><SectionHeading title="Create a draft" description="Drafts stay editable until you publish them. Eligibility and lifecycle checks remain server-authoritative."/><OpportunityFields organizationId={org.id} action={createOpportunity}/></section>
  </main>;
}

function OpportunityGroup({ title, description, items, participants }: { title: string; description: string; items: Opportunity[]; participants: Participation[] }) { if (!items.length) return null; return <div className="opportunity-group"><div className="group-heading"><h3>{title}</h3><p>{description}</p></div><div className="stack">{items.map((item) => <OpportunityCard key={item.id} item={item} participantCount={participants.filter((participation) => participation.opportunity_id === item.id && participation.status === 'joined').length}/>)}</div></div>; }
function OpportunityCard({ item, participantCount }: { item: Opportunity; participantCount: number }) { const past = item.status === 'published' && item.due_at && new Date(item.due_at) <= new Date(); return <article className="card opportunity-card"><div className="card-title"><div><h3>{item.title}</h3><p>{labels[item.category] || item.category} · {item.mode === 'scheduled' ? `Scheduled · ${date(item.starts_at)}–${date(item.ends_at)}` : `Flexible / remote · due ${date(item.due_at)}`}</p></div><Badge value={item.status}/></div><dl className="context-list opportunity-context"><div><dt>Capacity</dt><dd>{participantCount} active / {item.capacity} places</dd></div><div><dt>Eligible time</dt><dd>{item.expected_eligible_minutes} minutes</dd></div><div><dt>Location</dt><dd>{item.city || (item.mode === 'flexible_remote' ? 'Remote' : 'Not listed')}</dd></div><div><dt>Next step</dt><dd>{item.status === 'draft' ? 'Review and publish' : item.status === 'cancelled' ? 'Historical record' : past ? 'Review participation history' : 'Monitor participation'}</dd></div></dl>{item.status === 'draft' && <details className="edit-panel"><summary>Edit draft</summary><p className="helper">These fields are locked after publishing.</p><OpportunityFields organizationId={item.organization_id} item={item} action={updateOpportunity}/></details>}<div className="action-row">{item.status === 'draft' && <OperationalForm action={publishOpportunity}><input type="hidden" name="id" value={item.id}/><SubmitButton>Publish opportunity</SubmitButton></OperationalForm>}{['draft', 'published'].includes(item.status) && !past && <details className="danger-disclosure"><summary>Cancel opportunity</summary><OperationalForm action={cancelOpportunity} className="inline-form danger-panel" confirmation="Cancel this opportunity? The existing server lifecycle will protect participant outcomes."><input type="hidden" name="id" value={item.id}/><Field label="Cancellation reason"><textarea name="reason" required minLength={3} maxLength={500}/></Field><p className="helper">Cancellation cannot be undone. Participant outcomes are handled by the existing lifecycle rules.</p><SubmitButton className="btn danger">Cancel opportunity</SubmitButton></OperationalForm></details>}</div></article>; }
function ParticipationCard({ item, opportunity }: { item: Participation; opportunity: Opportunity }) { const action = participationAction(item, opportunity); return <article className="card participant-card"><div className="card-title"><div><h3>Participant #{item.student_id.slice(-6)}</h3><p>{opportunity.title} · joined {date(item.joined_at)}</p></div><Badge value={item.status}/></div>{action === 'resolve_scheduled' && <div className="participant-action"><p className="helper">The scheduled opportunity has ended. Confirm completion only when the work is complete, or record the permitted outcome.</p><div className="action-row"><OperationalForm action={verifyParticipation}><input type="hidden" name="id" value={item.id}/><SubmitButton>Verify completion</SubmitButton></OperationalForm><ResolutionActions id={item.id} allowNoShow /></div></div>}{action === 'verify_flexible' && <div className="participant-action"><p className="helper">Confirm completion only when the flexible work is complete. No-show is not available for flexible opportunities.</p><OperationalForm action={verifyParticipation}><input type="hidden" name="id" value={item.id}/><SubmitButton>Verify completion</SubmitButton></OperationalForm></div>}{action === 'waiting_for_scheduled_end' && <p className="form-note">No action yet. Completion or resolution becomes available after the scheduled end time.</p>}{action === 'admin_review' && <p className="form-note">This record is in CINSTE Admin review. Operators can inspect its context but cannot resolve or verify it here.</p>}{action === 'history' && <p className="form-note">Resolved record. Its trusted completion and resolution history are retained by the existing system.</p>}</article>; }
function ResolutionActions({ id, allowNoShow }: { id: string; allowNoShow: boolean }) { return <details className="danger-disclosure"><summary>Record another outcome</summary><OperationalForm action={resolveParticipation} className="inline-form"><input type="hidden" name="id" value={id}/><Field label="Outcome"><select name="outcome" defaultValue="excused"><option value="excused">Excused</option>{allowNoShow && <option value="no_show">No show</option>}</select></Field><Field label="Reason"><textarea name="reason" required minLength={3} maxLength={500}/></Field><SubmitButton className="btn secondary">Record outcome</SubmitButton></OperationalForm></details>; }
function OpportunityFields({ organizationId, item, action }: { organizationId: string; item?: Opportunity; action: Parameters<typeof OperationalForm>[0]['action'] }) { return <OperationalForm action={action} className="form-grid"><input type="hidden" name="organizationId" value={organizationId}/>{item && <input type="hidden" name="id" value={item.id}/>}<Field label="Opportunity title"><input name="title" defaultValue={item?.title} required minLength={2}/></Field><Field label="Category"><select name="category" defaultValue={item?.category ?? 'community'}>{categories.map((category) => <option key={category} value={category}>{category[0].toUpperCase() + category.slice(1)}</option>)}</select></Field><Field label="Description" wide><textarea name="description" defaultValue={item?.description} required/></Field><Field label="Format"><select name="mode" defaultValue={item?.mode ?? 'flexible_remote'}><option value="flexible_remote">Flexible / remote</option><option value="scheduled">Scheduled</option></select></Field><Field label="City or location"><input name="city" defaultValue={item?.city ?? ''}/></Field><Field label="Due date and time"><input name="dueAt" type="datetime-local" defaultValue={localDate(item?.due_at ?? null)} required/></Field><Field label="Start date and time (scheduled only)"><input name="startsAt" type="datetime-local" defaultValue={localDate(item?.starts_at ?? null)}/></Field><Field label="End date and time (scheduled only)"><input name="endsAt" type="datetime-local" defaultValue={localDate(item?.ends_at ?? null)}/></Field><Field label="Eligible minutes"><input name="minutes" type="number" min="1" max="1440" defaultValue={item?.expected_eligible_minutes} required/></Field><Field label="Capacity"><input name="capacity" type="number" min="1" defaultValue={item?.capacity} required/></Field><div className="form-actions"><SubmitButton>{item ? 'Save draft changes' : 'Save draft'}</SubmitButton></div></OperationalForm>; }
function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={`field${wide ? ' wide' : ''}`}><span>{label}</span>{children}</label>; }
function Badge({ value }: { value: string }) { return <span className={`status status-${value}`}>{labels[value] || value.replaceAll('_', ' ')}</span>; }
function SectionHeading({ title, description }: { title: string; description: string }) { return <div className="section-heading"><h2>{title}</h2><p>{description}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="empty-state">{text}</div>; }
function WorkspaceError() { return <div className="empty-state error-state"><strong>Workspace data could not be loaded.</strong><p>Refresh the page and try again. No action queue is shown until the authorized data is available.</p></div>; }
