import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { selectAssignedOrganization } from '@/lib/organization-selection';
import { OperationalForm, SubmitButton } from '@/components/operational-form';
import { cancelOpportunity, createOpportunity, publishOpportunity, resolveParticipation, updateOpportunity, verifyParticipation } from './actions';

const categories = ['community', 'education', 'environment', 'animals', 'events', 'skills', 'other'];
const labels: Record<string, string> = { draft: 'Draft', published: 'Published', cancelled: 'Cancelled', joined: 'Joined', completed: 'Completed', disputed: 'Disputed', overdue: 'Overdue review', no_show: 'No show', excused: 'Excused', cancelled_by_organization: 'Cancelled by organization', late_cancelled: 'Late cancellation', expired_incomplete: 'Expired incomplete' };
const localDate = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : '';
const date = (value: string | null) => value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not recorded';

export default async function Organization({ searchParams }: { searchParams: Promise<{ organizationId?: string }> }) {
  const db = await createClient(); const { data: { user } } = await db.auth.getUser(); if (!user) redirect('/login');
  const selectedOrganizationId = (await searchParams).organizationId;
  const [{ data: organizations }, { data: opportunities }, { data: participations }] = await Promise.all([
    db.from('organizations').select('id,name,status'),
    db.from('impact_opportunities').select('id,organization_id,title,description,category,status,mode,city,starts_at,ends_at,due_at,expected_eligible_minutes,capacity').order('created_at', { ascending: false }),
    db.from('impact_participations').select('id,opportunity_id,student_id,status,joined_at').order('joined_at', { ascending: false }),
  ]);
  if (!organizations?.length) redirect('/?error=Organization access required');
  const org = selectAssignedOrganization(organizations, selectedOrganizationId); if (!org) redirect('/?error=Organization access required'); const own = opportunities?.filter((row) => row.organization_id === org.id) ?? []; const ownIds = new Set(own.map((row) => row.id)); const participants = participations?.filter((row) => ownIds.has(row.opportunity_id)) ?? [];
  const participantGroups = { action: participants.filter((item) => item.status === 'joined'), review: participants.filter((item) => ['overdue', 'disputed'].includes(item.status)), history: participants.filter((item) => !['joined', 'overdue', 'disputed'].includes(item.status)) };
  return <main className="shell operational-shell py-10"><div className="page-heading"><div><p className="eyebrow">Impact operations</p><h1>{org.name}</h1><p>Manage only this organization’s opportunities and participant outcomes.</p></div><Badge value={org.status}/></div>{organizations.length > 1 && <form method="get" className="organization-selector"><label htmlFor="organizationId">Organization</label><div><select id="organizationId" name="organizationId" defaultValue={org.id}>{organizations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="btn secondary">Switch organization</button></div></form>}
    <section className="card form-card"><h2>Create an opportunity</h2><p className="helper">Save as a draft first. Only drafts can be edited; publishing and eligibility stay enforced by the existing server rules.</p><OpportunityFields organizationId={org.id} action={createOpportunity}/></section>
    <section className="section-block"><SectionHeading title="Opportunities" description="Drafts are editable. Published opportunities are available under the existing lifecycle and capacity rules."/><div className="stack">{own.map((item) => <article className="card opportunity-card" key={item.id}><div className="card-title"><div><h3>{item.title}</h3><p>{labels[item.category] || item.category} · {item.mode === 'scheduled' ? 'Scheduled' : 'Flexible / remote'} · due {date(item.due_at)}</p></div><Badge value={item.status}/></div><div className="opportunity-meta"><span><strong>{item.expected_eligible_minutes}</strong> eligible minutes</span><span><strong>{item.capacity}</strong> places</span><span>{item.city || (item.mode === 'flexible_remote' ? 'Remote' : 'Location not listed')}</span></div>{item.status === 'draft' && <details className="edit-panel"><summary>Edit draft</summary><p className="helper">These fields are locked after publishing.</p><OpportunityFields organizationId={org.id} item={item} action={updateOpportunity}/></details>}<div className="action-row">{item.status === 'draft' && <OperationalForm action={publishOpportunity}><input type="hidden" name="id" value={item.id}/><SubmitButton>Publish opportunity</SubmitButton></OperationalForm>}{['draft', 'published'].includes(item.status) && <details className="danger-disclosure"><summary>Cancel opportunity</summary><OperationalForm action={cancelOpportunity} className="inline-form danger-panel" confirmation="Cancel this opportunity? The existing server lifecycle will protect participant outcomes."><input type="hidden" name="id" value={item.id}/><Field label="Cancellation reason"><textarea name="reason" required minLength={3} maxLength={500}/></Field><p className="helper">Cancellation cannot be undone. Participant outcomes are handled by the existing lifecycle rules.</p><SubmitButton className="btn danger">Cancel opportunity</SubmitButton></OperationalForm></details>}</div></article>)}{!own.length && <Empty text="No opportunities yet. Create a draft to start planning a contribution activity."/>}</div></section>
    <section className="section-block"><SectionHeading title="Participants" description="Only minimal identifiers for participants in this organization’s opportunities are shown."/><ParticipantGroup title="Needs action" items={participantGroups.action} action/><ParticipantGroup title="Needs review" items={participantGroups.review}/><ParticipantGroup title="History" items={participantGroups.history}/>{!participants.length && <Empty text="Participants will appear here after students join a published opportunity."/>}</section>
  </main>;
}

function ParticipantGroup({ title, items, action }: { title: string; items: { id: string; student_id: string; status: string; joined_at: string | null }[]; action?: boolean }) { if (!items.length) return null; return <div className="participant-group"><h3>{title} <span>{items.length}</span></h3>{items.map((item) => <article className="card participant-card" key={item.id}><div className="card-title"><div><h4>Participant #{item.student_id.slice(-6)}</h4><p>Joined {date(item.joined_at)}</p></div><Badge value={item.status}/></div>{action && <div className="action-row"><OperationalForm action={verifyParticipation}><input type="hidden" name="id" value={item.id}/><p className="helper">Confirm only completed work. Your own student participation cannot be verified here.</p><SubmitButton>Verify completion</SubmitButton></OperationalForm><details className="danger-disclosure"><summary>Record an excusal</summary><OperationalForm action={resolveParticipation} className="inline-form"><input type="hidden" name="id" value={item.id}/><input type="hidden" name="outcome" value="excused"/><Field label="Excusal reason"><textarea name="reason" required minLength={3} maxLength={500}/></Field><SubmitButton className="btn secondary">Record excusal</SubmitButton></OperationalForm></details></div>}</article>)}</div>; }
function OpportunityFields({ organizationId, item, action }: { organizationId: string; item?: any; action: Parameters<typeof OperationalForm>[0]['action'] }) { return <OperationalForm action={action} className="form-grid"><input type="hidden" name="organizationId" value={organizationId}/>{item && <input type="hidden" name="id" value={item.id}/>}<Field label="Opportunity title"><input name="title" defaultValue={item?.title} required minLength={2}/></Field><Field label="Category"><select name="category" defaultValue={item?.category ?? 'community'}>{categories.map((category) => <option key={category} value={category}>{category[0].toUpperCase() + category.slice(1)}</option>)}</select></Field><Field label="Description" wide><textarea name="description" defaultValue={item?.description} required/></Field><Field label="Format"><select name="mode" defaultValue={item?.mode ?? 'flexible_remote'}><option value="flexible_remote">Flexible / remote</option><option value="scheduled">Scheduled</option></select></Field><Field label="City or location"><input name="city" defaultValue={item?.city ?? ''}/></Field><Field label="Due date and time"><input name="dueAt" type="datetime-local" defaultValue={localDate(item?.due_at ?? null)} required/></Field><Field label="Start date and time (scheduled only)"><input name="startsAt" type="datetime-local" defaultValue={localDate(item?.starts_at ?? null)}/></Field><Field label="End date and time (scheduled only)"><input name="endsAt" type="datetime-local" defaultValue={localDate(item?.ends_at ?? null)}/></Field><Field label="Eligible minutes"><input name="minutes" type="number" min="1" max="1440" defaultValue={item?.expected_eligible_minutes} required/></Field><Field label="Capacity"><input name="capacity" type="number" min="1" defaultValue={item?.capacity} required/></Field><div className="form-actions"><SubmitButton>{item ? 'Save draft changes' : 'Save draft'}</SubmitButton></div></OperationalForm>; }
function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={`field${wide ? ' wide' : ''}`}><span>{label}</span>{children}</label>; }
function Badge({ value }: { value: string }) { return <span className={`status status-${value}`}>{labels[value] || value.replaceAll('_', ' ')}</span>; }
function SectionHeading({ title, description }: { title: string; description: string }) { return <div className="section-heading"><h2>{title}</h2><p>{description}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="empty-state">{text}</div>; }
