import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { AdminNav } from '@/components/admin-nav';
import { OperationalForm, SubmitButton } from '@/components/operational-form';
import { reviewVerification } from './actions';

const date = (value: string | null) => value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not recorded';
const labels: Record<string, string> = { active: 'Active', pending: 'Pending', pending_review: 'Pending review', failed: 'Failed', overdue: 'Overdue review', disputed: 'Disputed', suspended: 'Suspended' };

export default async function Admin() {
  const db = await createClient(); const { data: { user } } = await db.auth.getUser(); if (!user) redirect('/login');
  const { data: me } = await db.from('profiles').select('role').eq('id', user.id).single(); if (me?.role !== 'admin') redirect('/?error=Admin access required');
  const [{ data: pendingVerifications, error: verificationError }, { data: impactParticipation, error: participationError }, { data: reviewRequests, error: reviewError }, { data: lowInventory, error: campaignError }, { data: pendingOrganizations, error: organizationError }, { data: paymentExceptions, error: paymentError }] = await Promise.all([
    db.from('student_verifications').select('id,full_name,status,submitted_at,universities(name)').eq('status', 'pending').order('submitted_at').limit(20),
    db.from('impact_participations').select('id,status,joined_at,impact_opportunities(title,organizations(name))').in('status', ['overdue', 'disputed']).order('joined_at').limit(20),
    db.from('impact_overdue_review_requests').select('participation_id,requested_at').order('requested_at', { ascending: false }).limit(20),
    db.from('campaigns').select('id,name,quantity_available,ends_at,offers(name,partners(name))').eq('status', 'active').eq('quantity_available', 0).order('ends_at').limit(20),
    db.from('organizations').select('id,name,status,city').in('status', ['pending_review', 'suspended']).order('created_at', { ascending: false }).limit(20),
    db.from('payments').select('id,status,created_at,giver_orders(status)').in('status', ['pending', 'failed']).order('created_at', { ascending: false }).limit(20),
  ]);
  const requestByParticipation = new Map((reviewRequests ?? []).map((item) => [item.participation_id, item]));
  const attentionCount = (pendingVerifications?.length ?? 0) + (impactParticipation?.length ?? 0) + (lowInventory?.length ?? 0) + (pendingOrganizations?.length ?? 0);
  return <main className="shell operational-shell admin-v1-page py-10">
    <div className="page-heading"><div><p className="eyebrow">CINSTE operations</p><h1>Admin workspace</h1><p>Review the records that need a decision, then move to the relevant operational area.</p></div><span className="admin-attention">{attentionCount} attention items</span></div><AdminNav current="/admin" />
    <section id="attention" className="section-block"><SectionHeading title="Needs attention" description="Only records with an existing Admin action or an operational follow-up appear here."/><div className="admin-queue-grid">
      <Queue title="Student verification" href="#verification" count={pendingVerifications?.length ?? 0} error={verificationError} empty="No student documents are waiting for review.">{pendingVerifications?.map((item: any) => <article className="admin-queue-item" key={item.id}><div><strong>{item.full_name}</strong><p>{item.universities?.name || 'University unavailable'} · submitted {date(item.submitted_at)}</p></div><Link className="text-link" href="#verification">Review</Link></article>)}</Queue>
      <Queue title="Impact Admin review" href="/admin/impact#participation" count={impactParticipation?.length ?? 0} error={participationError || reviewError} empty="No overdue or disputed participation is awaiting Admin review.">{impactParticipation?.map((item: any) => <article className="admin-queue-item" key={item.id}><div><strong>{item.impact_opportunities?.title || 'Impact opportunity'}</strong><p>{item.impact_opportunities?.organizations?.name || 'Organization unavailable'} · <Status value={item.status}/>{requestByParticipation.has(item.id) && ' · student review request received'}</p></div><Link className="text-link" href="/admin/impact#participation">Review</Link></article>)}</Queue>
      <Queue title="Campaign inventory" href="/admin/manage#campaigns" count={lowInventory?.length ?? 0} error={campaignError} empty="No active campaign is currently recorded with zero available inventory.">{lowInventory?.map((item: any) => <article className="admin-queue-item" key={item.id}><div><strong>{item.name}</strong><p>{item.offers?.name || 'Offer unavailable'} · {item.offers?.partners?.name || 'Partner unavailable'} · ends {date(item.ends_at)}</p></div><Link className="text-link" href="/admin/manage#campaigns">Manage</Link></article>)}</Queue>
      <Queue title="Organizations" href="/admin/impact#organizations" count={pendingOrganizations?.length ?? 0} error={organizationError} empty="No pending or suspended organization needs a lifecycle decision.">{pendingOrganizations?.map((item) => <article className="admin-queue-item" key={item.id}><div><strong>{item.name}</strong><p>{item.city || 'City unavailable'} · <Status value={item.status}/></p></div><Link className="text-link" href="/admin/impact#organizations">Manage</Link></article>)}</Queue>
    </div></section>
    <section id="verification" className="section-block"><SectionHeading title="Student verification" description="Open documents through the protected review route. Approve or reject only after reviewing the submitted document."/>{verificationError ? <LoadError text="Student verification records could not be loaded."/> : pendingVerifications?.length ? <div className="stack">{pendingVerifications.map((item: any) => <article className="card operation-card" key={item.id}><div className="card-title"><div><h3>{item.full_name}</h3><p>{item.universities?.name || 'University unavailable'} · submitted {date(item.submitted_at)}</p></div><Status value={item.status}/></div><div className="action-row"><a className="btn secondary" href={`/api/admin/verifications/${item.id}/document`} target="_blank" rel="noreferrer">Open submitted document</a><OperationalForm action={reviewVerification}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="decision" value="verified"/><SubmitButton>Approve verification</SubmitButton></OperationalForm><details className="danger-disclosure"><summary>Reject submission</summary><OperationalForm action={reviewVerification} className="inline-form danger-panel" confirmation="Reject this verification? The reason will be shown to the student."><input type="hidden" name="id" value={item.id}/><input type="hidden" name="decision" value="rejected"/><Field label="Reason for student"><textarea name="rejectionReason" required minLength={3} maxLength={500}/></Field><SubmitButton className="btn danger">Reject verification</SubmitButton></OperationalForm></details></div></article>)}</div> : <Empty text="No student verification is waiting for review."/>}</section>
    <section className="section-block"><SectionHeading title="Operational watch" description="These read-only payment states may need follow-up outside the product. CINSTE has no Admin payment override in V1."/>{paymentError ? <LoadError text="Payment exception records could not be loaded."/> : paymentExceptions?.length ? <div className="stack">{paymentExceptions.map((item: any) => <article className="card compact-row" key={item.id}><div><strong><Status value={item.status}/></strong><p>Recorded {date(item.created_at)} · related order is {item.giver_orders?.status || 'unavailable'}</p></div><Link className="text-link" href="/admin/operations#payments">View operational records</Link></article>)}</div> : <Empty text="No pending or failed payment records are in the recent operational view."/>}</section>
  </main>;
}
function Queue({ title, href, count, error, empty, children }: { title: string; href: string; count: number; error: unknown; empty: string; children: React.ReactNode }) { return <section className="card admin-queue"><div className="card-title"><div><h3>{title}</h3><p>{count} record{count === 1 ? '' : 's'}</p></div><Link className="text-link" href={href}>Open</Link></div>{error ? <LoadError text={`${title} could not be loaded.`}/> : count ? <div className="admin-queue-list">{children}</div> : <p className="empty-inline">{empty}</p>}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Status({ value }: { value: string }) { return <span className={`status status-${value}`}>{labels[value] || value.replaceAll('_', ' ')}</span>; }
function SectionHeading({ title, description }: { title: string; description: string }) { return <div className="section-heading"><h2>{title}</h2><p>{description}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="empty-state">{text}</div>; }
function LoadError({ text }: { text: string }) { return <div className="empty-state error-state"><strong>{text}</strong><p>Refresh the page and try again.</p></div>; }
