import { useCallback, useEffect, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as Crypto from 'expo-crypto';
import * as DocumentPicker from 'expo-document-picker';
import * as ImagePicker from 'expo-image-picker';
import { Redirect, useFocusEffect } from 'expo-router';

import { Button, Card, Loading, colors } from '@/components/ui';
import { useAuth } from '@/context/auth';
import { useAppLocale } from '@/i18n';
import { supabase } from '@/lib/supabase';
import { resolveMobileDestination } from '@/lib/mobile-routing';

type Picked = { uri: string; name: string; mimeType: string; size: number };
const accepted = ['application/pdf', 'image/jpeg', 'image/png']; const maximumDocumentBytes = 5 * 1024 * 1024;
export default function Verification() {
  const { session, loading, role, student, refreshStudent } = useAuth(); const { t, isRTL } = useAppLocale(); const [universities, setUniversities] = useState<{ id: string; name: string }[]>([]); const [fullName, setFullName] = useState(student?.full_name ?? ''); const [faculty, setFaculty] = useState(student?.faculty ?? ''); const [universityId, setUniversityId] = useState(student?.university_id ?? ''); const [document, setDocument] = useState<Picked>(); const [busy, setBusy] = useState(false);
  useEffect(() => { supabase.from('universities').select('id,name').eq('active', true).order('sort_order').then(({ data }) => setUniversities(data ?? [])); }, []);
  useFocusEffect(useCallback(() => { void refreshStudent(); }, [refreshStudent]));
  const destination = resolveMobileDestination({ hasSession: Boolean(session), resolved: !loading, role, verificationStatus: student?.verification_status ?? null });
  if (destination === 'loading') return <Loading label={t('common.loading')} />;
  if (destination === 'login') return <Redirect href="/(auth)/login"/>;
  if (destination === 'student') return <Redirect href="/(student)/(tabs)"/>;
  if (destination === 'role-boundary') return <Redirect href="/role-boundary"/>;
  if (!session) return <Loading label={t('common.loading')} />;
  if (student?.verification_status === 'pending') return <ScrollView contentContainerStyle={[styles.page, isRTL && styles.rtl]}><Text style={[styles.title, isRTL && styles.textRtl]}>{t('verification.pendingTitle')}</Text><Card><Text style={[styles.copy, isRTL && styles.textRtl]}>{t('verification.pendingCopy')}</Text></Card></ScrollView>;
  const validate = (asset: Picked) => { if (!accepted.includes(asset.mimeType) || asset.size > maximumDocumentBytes) { Alert.alert(t('verification.invalidDocumentTitle'), t('verification.invalidDocument')); return; } setDocument(asset); };
  const chooseFile = async () => { const result = await DocumentPicker.getDocumentAsync({ type: accepted, copyToCacheDirectory: true }); if (!result.canceled) { const asset = result.assets[0]; validate({ uri: asset.uri, name: asset.name, mimeType: asset.mimeType ?? 'application/octet-stream', size: asset.size ?? 0 }); } };
  const chooseImage = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.9 }); if (!result.canceled) { const asset = result.assets[0]; validate({ uri: asset.uri, name: asset.fileName ?? 'student-document.jpg', mimeType: asset.mimeType ?? 'image/jpeg', size: asset.fileSize ?? 0 }); } };
  const submit = async () => { if (!fullName.trim() || !universityId || !document) return Alert.alert(t('verification.missingTitle'), t('verification.missing')); setBusy(true); try { const raw = await fetch(document.uri).then((response) => response.arrayBuffer()); const path = `${session.user.id}/${Crypto.randomUUID()}-${document.name.replace(/[^a-zA-Z0-9._-]/g, '_')}`; const { error: uploadError } = await supabase.storage.from('student-documents').upload(path, raw, { contentType: document.mimeType, upsert: false }); if (uploadError) throw uploadError; const { error: submissionError } = await supabase.rpc('submit_student_verification', { p_full_name: fullName.trim(), p_university_id: universityId, p_faculty: faculty.trim() || null, p_document_path: path, p_document_mime: document.mimeType, p_document_bytes: document.size }); if (submissionError) throw submissionError; await refreshStudent(); Alert.alert(t('verification.successTitle'), t('verification.success')); } catch { Alert.alert(t('verification.errorTitle'), t('error.generic')); } finally { setBusy(false); } };
  const rejected = student?.verification_status === 'rejected';
  return <ScrollView contentContainerStyle={[styles.page, isRTL && styles.rtl]}><Text style={[styles.title, isRTL && styles.textRtl]}>{t(rejected ? 'verification.rejectedTitle' : 'verification.title')}</Text><Text style={[styles.subtitle, isRTL && styles.textRtl]}>{t(rejected ? 'verification.rejectedCopy' : 'verification.subtitle')}</Text>{rejected && <Card><Text style={[styles.label, isRTL && styles.textRtl]}>{t('verification.rejectionReason')}</Text><Text style={[styles.copy, isRTL && styles.textRtl]}>{student?.rejection_reason ?? t('error.generic')}</Text></Card>}<Card><Text style={[styles.label, isRTL && styles.textRtl]}>{t('auth.fullName')}</Text><TextInput value={fullName} onChangeText={setFullName} style={[styles.input, isRTL && styles.textRtl]} textAlign={isRTL ? 'right' : 'left'} /><Text style={[styles.label, isRTL && styles.textRtl]}>{t('verification.university')}</Text><View style={styles.universities}>{universities.map((university) => <Button key={university.id} label={university.name} variant={universityId === university.id ? 'primary' : 'quiet'} onPress={() => setUniversityId(university.id)} />)}</View><Text style={[styles.label, isRTL && styles.textRtl]}>{t('verification.faculty')}</Text><TextInput value={faculty} onChangeText={setFaculty} style={[styles.input, isRTL && styles.textRtl]} textAlign={isRTL ? 'right' : 'left'} /><Text style={[styles.label, isRTL && styles.textRtl]}>{t('verification.document')}</Text><Text style={[styles.helper, isRTL && styles.textRtl]}>{t('verification.documentHint')}</Text><View style={styles.actions}><Button label={t('verification.pickDocument')} variant="quiet" onPress={chooseFile}/><Button label={t('verification.pickPhoto')} variant="quiet" onPress={chooseImage}/></View>{document && <Text style={[styles.file, isRTL && styles.textRtl]}>✓ {document.name}</Text>}<View style={{ marginTop: 18 }}><Button label={t(busy ? 'verification.submitting' : rejected ? 'verification.resubmit' : 'verification.submit')} disabled={busy} onPress={submit}/></View></Card></ScrollView>;
}
const styles = StyleSheet.create({ page: { padding: 20, gap: 14, backgroundColor: colors.cream }, rtl: { direction: 'rtl' }, textRtl: { textAlign: 'right', writingDirection: 'rtl' }, title: { fontSize: 36, fontWeight: '900', letterSpacing: -1.2, color: colors.ink }, subtitle: { fontSize: 16, lineHeight: 23, color: colors.muted }, copy: { fontSize: 16, lineHeight: 23, color: colors.muted }, label: { fontWeight: '900', fontSize: 14, color: colors.ink, marginTop: 15 }, input: { height: 50, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 14, fontSize: 16, marginTop: 7 }, universities: { gap: 8, marginTop: 8 }, helper: { color: colors.muted, fontSize: 13, marginTop: 5 }, actions: { gap: 8, marginTop: 12 }, file: { fontWeight: '800', color: colors.forest, marginTop: 12 } });
