import { useCallback, useState } from 'react';
import { Alert, Linking, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';

import { Button, Card, Loading, Pill, colors } from '@/components/ui';
import { useAuth } from '@/context/auth';
import { formatDate, localizedAvailabilityAndFree, localizedCategory, localizedClaimError, localizedOffer, useAppLocale } from '@/i18n';
import { fulfillmentEmoji, fulfillmentLabel } from '@/lib/presentation';
import { supabase } from '@/lib/supabase';
import type { CampaignCard } from '@/lib/types';

export default function OfferDetail() {
  const { campaignId } = useLocalSearchParams<{ campaignId: string }>(); const { refreshStudent } = useAuth(); const { t, locale, isRTL } = useAppLocale();
  const [campaign, setCampaign] = useState<CampaignCard>(); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const { data, error } = await supabase.from('campaigns').select('id,name,quantity_available,ends_at,event_starts_at,offers!inner(id,localization_key,name,description,fulfillment_type,redemption_instructions,booking_url,partners(name,address),categories(name,slug))').eq('id', campaignId).single(); if (error) { setCampaign(undefined); Alert.alert(t('offer.notFound'), t('error.generic')); } else setCampaign(data as unknown as CampaignCard); }, [campaignId, t]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (!campaign) return <Loading label={t('common.loading')} />;
  const offer = localizedOffer(campaign.offers, t);
  const claim = async () => { const refreshedStudent = await refreshStudent(); if (refreshedStudent?.verification_status !== 'verified') { router.push('/verification'); return; } setBusy(true); try { const { data, error } = await supabase.rpc('claim_campaign', { p_campaign_id: campaign.id }); if (error) return Alert.alert(t('offer.claimErrorTitle'), localizedClaimError(error.message, t)); const result = data?.[0]; if (!result?.claim_id) return Alert.alert(t('offer.claimErrorTitle'), localizedClaimError(undefined, t)); router.replace({ pathname: '/(student)/claim/[claimId]', params: { claimId: result.claim_id } }); } catch { Alert.alert(t('offer.claimErrorTitle'), localizedClaimError(undefined, t)); } finally { setBusy(false); } };
  return <ScrollView contentContainerStyle={[styles.page, isRTL && styles.rtl]}>
    <View style={styles.hero}><Text style={styles.emoji}>{fulfillmentEmoji(offer.fulfillment_type)}</Text></View><Pill rtl={isRTL}>{localizedCategory(offer.categories.slug, t, offer.categories.name)}</Pill><Text style={[styles.title, isRTL && styles.textRtl]}>{offer.name}</Text><Text style={[styles.description, isRTL && styles.textRtl]}>{offer.description}</Text>
    <Card style={styles.info}><Text style={[styles.label, isRTL && styles.textRtl]}>{t('offer.partner')}</Text><Text style={[styles.value, isRTL && styles.textRtl]}>{offer.partners.name}</Text><Text style={[styles.address, isRTL && styles.textRtl]}>{offer.partners.address}</Text><View style={styles.line}/><Text style={[styles.fulfillment, isRTL && styles.textRtl]}>{fulfillmentLabel(offer.fulfillment_type, t)}</Text>{offer.fulfillment_type === 'scheduled_event' && campaign.event_starts_at && <Text style={[styles.detail, isRTL && styles.textRtl]}>{t('offer.event', { date: formatDate(campaign.event_starts_at, locale) })}</Text>}{offer.fulfillment_type === 'appointment_required' && <><Text style={[styles.detail, isRTL && styles.textRtl]}>{t('offer.bookBefore')}</Text>{offer.booking_url && <Button label={t('offer.openBooking')} variant="quiet" onPress={() => Linking.openURL(offer.booking_url!)}/>}</>}<Text style={[styles.available, isRTL && styles.textRtl]}>{localizedAvailabilityAndFree(campaign.quantity_available, locale, t)}</Text>{offer.redemption_instructions && <Text style={[styles.instructions, isRTL && styles.textRtl]}>{offer.redemption_instructions}</Text>}</Card>
    <Text style={[styles.note, isRTL && styles.textRtl]}>{t('offer.reserveNote')}</Text><Button label={t(busy ? 'offer.claiming' : 'offer.claim')} disabled={busy} onPress={claim}/>
  </ScrollView>;
}
const styles = StyleSheet.create({ page: { padding: 20, gap: 14, backgroundColor: colors.cream }, rtl: { direction: 'rtl' }, textRtl: { textAlign: 'right', writingDirection: 'rtl' }, hero: { height: 170, borderRadius: 28, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' }, emoji: { fontSize: 70 }, title: { fontSize: 37, fontWeight: '900', letterSpacing: -1.4, color: colors.ink }, description: { fontSize: 17, lineHeight: 25, color: colors.muted }, info: { gap: 5 }, label: { fontSize: 13, fontWeight: '800', color: colors.muted, textTransform: 'uppercase' }, value: { fontSize: 20, fontWeight: '900', color: colors.ink }, address: { fontSize: 15, color: colors.muted }, line: { height: 1, backgroundColor: colors.border, marginVertical: 12 }, fulfillment: { fontSize: 16, fontWeight: '900', color: colors.forest }, detail: { fontSize: 15, lineHeight: 22, color: colors.ink, marginTop: 5 }, available: { fontWeight: '900', color: colors.coral, marginTop: 12 }, instructions: { fontSize: 14, lineHeight: 21, color: colors.muted, marginTop: 6 }, note: { fontSize: 13, lineHeight: 19, color: colors.muted, textAlign: 'center', paddingHorizontal: 12 } });
