const baseTranslations = {
  ro: {
    'common.loading': 'Se încarcă…', 'common.back': 'Înapoi', 'common.retry': 'Încearcă din nou', 'common.cancel': 'Anulează', 'common.confirm': 'Confirmă', 'common.free': 'GRATIS',
    'auth.login.title': 'Bine ai venit', 'auth.login.subtitle': 'Intră ca să vezi cine face cinste azi.', 'auth.login.submit': 'Intră', 'auth.login.submitting': 'Se verifică…', 'auth.login.noAccount': 'Nu ai cont? Creează unul', 'auth.login.errorTitle': 'Nu am putut intra',
    'auth.register.title': 'Fă parte din cinste', 'auth.register.subtitle': 'Contul tău nu înseamnă automat verificare de student.', 'auth.register.submit': 'Creează cont', 'auth.register.submitting': 'Se creează…', 'auth.register.hasAccount': 'Ai deja cont? Intră', 'auth.register.errorTitle': 'Nu am putut crea contul', 'auth.register.confirmEmailTitle': 'Verifică emailul', 'auth.register.confirmEmail': 'Confirmă adresa de email înainte să intri în cont.',
    'auth.email': 'Email', 'auth.password': 'Parolă', 'auth.fullName': 'Nume complet',
    'tabs.discover': 'Descoperă', 'tabs.myCinste': 'Cinstile mele', 'tabs.profile': 'Profil',
    'discover.kicker': 'PENTRU TINE', 'discover.title': 'Azi cine face cinste?', 'discover.subtitle': 'Experiențe bune, oferite studenților verificați.', 'discover.loading': 'Căutăm cinstile de azi…', 'discover.all': 'Toate', 'discover.available_zero': 'Nu mai sunt disponibile', 'discover.available_one': '{{formattedCount}} disponibilă', 'discover.available_two': '{{formattedCount}} disponibile', 'discover.available_few': '{{formattedCount}} disponibile', 'discover.available_many': '{{formattedCount}} disponibile', 'discover.available_other': '{{formattedCount}} disponibile', 'discover.availabilityFree': '{{availability}} · {{free}}', 'discover.emptyTitle': 'Momentan nu mai avem cinste disponibile.', 'discover.emptyCopy': 'Revino în curând. Pregătim următoarele.',
    'offer.notFound': 'Nu am găsit cinstea', 'offer.partner': 'Partener', 'offer.event': 'Eveniment: {{date}}', 'offer.bookBefore': 'Programează-te înainte de a merge.', 'offer.openBooking': 'Deschide programarea', 'offer.reserveNote': 'Poți lua o singură cinste la fiecare 24 de ore.', 'offer.claim': 'Ia-o', 'offer.claiming': 'Se rezervă…', 'offer.claimErrorTitle': 'Nu se poate rezerva',
    'claim.notFound': 'Nu am găsit cinstea', 'claim.active': 'Activă', 'claim.redeemed': 'Folosită', 'claim.expired': 'Expirată', 'claim.cancelled': 'Anulată', 'claim.showPartnerQr': 'Arată acest cod partenerului', 'claim.inactive': 'Această cinste nu mai poate fi folosită.', 'claim.expiresAt': 'Valabil până la {{date}}', 'claim.showManualCode': 'Ai nevoie de cod manual?', 'claim.hideManualCode': 'Ascunde codul manual',
    'myCinste.loading': 'Îți adunăm cinstile…', 'myCinste.active': 'Active', 'myCinste.history': 'Istoric', 'myCinste.noActive': 'Nu ai o cinste activă acum.', 'myCinste.noHistory': 'Aici vei găsi cinstile folosite și expirate.',
    'profile.title': 'Profilul meu', 'profile.howItWorks': 'Cum funcționează', 'profile.howItWorksCopy': 'O cinste este o experiență oferită de cineva. După verificare, poți rezerva una și o folosești cu codul QR la partener.', 'profile.logout': 'Ieși din cont', 'profile.language': 'Limbă', 'profile.chooseLanguage': 'Alege limba', 'profile.languageHint': 'Poți schimba limba oricând.',
    'verification.verified': 'Student verificat', 'verification.pending': 'Verificare în curs', 'verification.rejected': 'Verificare respinsă', 'verification.unverified': 'Nu ești verificat încă', 'verification.submitDocument': 'Trimite documentul', 'verification.pendingButton': 'Verificarea este în curs', 'verification.approvedTitle': 'Ești verificat', 'verification.approvedCopy': 'Poți lua o cinste disponibilă chiar acum.', 'verification.pendingTitle': 'Verificare în curs', 'verification.pendingCopy': 'Documentul tău este în curs de verificare. Te anunțăm aici când statutul se schimbă.', 'verification.title': 'Devino student verificat', 'verification.subtitle': 'Contul și verificarea sunt separate. Documentul ajunge doar la echipa CINSTE.', 'verification.university': 'Universitate', 'verification.faculty': 'Facultate (opțional)', 'verification.document': 'Document student', 'verification.documentHint': 'PDF, JPG sau PNG · maximum 5 MB', 'verification.pickDocument': 'Alege document', 'verification.pickPhoto': 'Alege fotografie', 'verification.submit': 'Trimite pentru verificare', 'verification.submitting': 'Se trimite…', 'verification.invalidDocumentTitle': 'Document invalid', 'verification.invalidDocument': 'Alege un PDF, JPG sau PNG mai mic de 5 MB.', 'verification.missingTitle': 'Lipsește ceva', 'verification.missing': 'Completează numele, universitatea și documentul.', 'verification.successTitle': 'Trimis pentru verificare', 'verification.success': 'Îți arătăm aici când documentul este aprobat.', 'verification.errorTitle': 'Nu am putut trimite documentul',
    'fulfillment.instant': 'Disponibil acum', 'fulfillment.appointment_required': 'Necesită programare', 'fulfillment.scheduled_event': 'Eveniment programat',
    'error.studentNotVerified': 'Ai nevoie de verificare aprobată înainte să iei o cinste.', 'error.claimLimit': 'Poți lua o singură cinste la fiecare 24 de ore.', 'error.soldOut': 'Cinstile s-au epuizat între timp.', 'error.campaignUnavailable': 'Această cinste nu este disponibilă acum.', 'error.genericClaim': 'Nu am putut rezerva cinstea. Încearcă din nou.', 'error.generic': 'A apărut o problemă. Încearcă din nou.',
    'category.food-drink': 'Mâncare și băuturi', 'category.cinema': 'Cinema', 'category.hair-grooming': 'Păr și îngrijire', 'category.beauty': 'Frumusețe și îngrijire', 'category.fitness': 'Fitness și sport', 'category.entertainment': 'Divertisment', 'category.activities': 'Activități', 'category.education': 'Educație', 'category.mobility': 'Mobilitate', 'category.other': 'Altele',
    'catalog.cappuccino.name': 'Cappuccino', 'catalog.cappuccino.description': 'O cafea bună, din partea cuiva.', 'catalog.cappuccino.redemption_instructions': 'Arată codul CINSTE la bar.', 'catalog.movie_ticket.name': 'Bilet la film', 'catalog.movie_ticket.description': 'Un bilet la o proiecție selectată.', 'catalog.movie_ticket.redemption_instructions': 'Prezintă codul QR la intrare.', 'catalog.student_haircut.name': 'Tunsoare pentru student', 'catalog.student_haircut.description': 'O tunsoare pentru studenți.', 'catalog.student_haircut.redemption_instructions': 'Programează-te telefonic și menționează CINSTE.',
  },
  en: {
    'common.loading': 'Loading…', 'common.back': 'Back', 'common.retry': 'Try again', 'common.cancel': 'Cancel', 'common.confirm': 'Confirm', 'common.free': 'FREE',
    'auth.login.title': 'Welcome back', 'auth.login.subtitle': 'Sign in to see who is treating today.', 'auth.login.submit': 'Sign in', 'auth.login.submitting': 'Signing in…', 'auth.login.noAccount': 'No account? Create one', 'auth.login.errorTitle': 'Could not sign in',
    'auth.register.title': 'Join CINSTE', 'auth.register.subtitle': 'Having an account does not automatically verify you as a student.', 'auth.register.submit': 'Create account', 'auth.register.submitting': 'Creating account…', 'auth.register.hasAccount': 'Already have an account? Sign in', 'auth.register.errorTitle': 'Could not create account', 'auth.register.confirmEmailTitle': 'Check your email', 'auth.register.confirmEmail': 'Confirm your email address before signing in.',
    'auth.email': 'Email', 'auth.password': 'Password', 'auth.fullName': 'Full name',
    'tabs.discover': 'Discover', 'tabs.myCinste': 'My treats', 'tabs.profile': 'Profile',
    'discover.kicker': 'FOR YOU', 'discover.title': 'Who is treating today?', 'discover.subtitle': 'Good experiences, offered to verified students.', 'discover.loading': 'Finding today’s treats…', 'discover.all': 'All', 'discover.available_zero': 'None available', 'discover.available_one': '{{formattedCount}} available', 'discover.available_two': '{{formattedCount}} available', 'discover.available_few': '{{formattedCount}} available', 'discover.available_many': '{{formattedCount}} available', 'discover.available_other': '{{formattedCount}} available', 'discover.availabilityFree': '{{availability}} · {{free}}', 'discover.emptyTitle': 'There are no treats available right now.', 'discover.emptyCopy': 'Come back soon. We’re preparing the next ones.',
    'offer.notFound': 'We could not find this treat', 'offer.partner': 'Partner', 'offer.event': 'Event: {{date}}', 'offer.bookBefore': 'Book before you go.', 'offer.openBooking': 'Open booking', 'offer.reserveNote': 'You can claim one treat every 24 hours.', 'offer.claim': 'Claim it', 'offer.claiming': 'Claiming…', 'offer.claimErrorTitle': 'Could not claim',
    'claim.notFound': 'We could not find this treat', 'claim.active': 'Active', 'claim.redeemed': 'Used', 'claim.expired': 'Expired', 'claim.cancelled': 'Cancelled', 'claim.showPartnerQr': 'Show this code to the partner', 'claim.inactive': 'This treat can no longer be used.', 'claim.expiresAt': 'Valid until {{date}}', 'claim.showManualCode': 'Need a manual code?', 'claim.hideManualCode': 'Hide manual code',
    'myCinste.loading': 'Collecting your treats…', 'myCinste.active': 'Active', 'myCinste.history': 'History', 'myCinste.noActive': 'You do not have an active treat right now.', 'myCinste.noHistory': 'Your used and expired treats will appear here.',
    'profile.title': 'My profile', 'profile.howItWorks': 'How it works', 'profile.howItWorksCopy': 'A treat is an experience offered by someone. After verification, you can claim one and use its QR code at the partner.', 'profile.logout': 'Sign out', 'profile.language': 'Language', 'profile.chooseLanguage': 'Choose language', 'profile.languageHint': 'You can change your language anytime.',
    'verification.verified': 'Verified student', 'verification.pending': 'Verification pending', 'verification.rejected': 'Verification rejected', 'verification.unverified': 'Not verified yet', 'verification.submitDocument': 'Submit document', 'verification.pendingButton': 'Verification in progress', 'verification.approvedTitle': 'You are verified', 'verification.approvedCopy': 'You can claim an available treat now.', 'verification.pendingTitle': 'Verification in progress', 'verification.pendingCopy': 'Your document is being reviewed. We will update this screen when your status changes.', 'verification.title': 'Get verified as a student', 'verification.subtitle': 'Your account and verification are separate. Only the CINSTE team receives your document.', 'verification.university': 'University', 'verification.faculty': 'Faculty (optional)', 'verification.document': 'Student document', 'verification.documentHint': 'PDF, JPG or PNG · maximum 5 MB', 'verification.pickDocument': 'Choose document', 'verification.pickPhoto': 'Choose photo', 'verification.submit': 'Submit for verification', 'verification.submitting': 'Submitting…', 'verification.invalidDocumentTitle': 'Invalid document', 'verification.invalidDocument': 'Choose a PDF, JPG, or PNG smaller than 5 MB.', 'verification.missingTitle': 'Something is missing', 'verification.missing': 'Add your name, university, and document.', 'verification.successTitle': 'Sent for review', 'verification.success': 'We will update this screen when your document is approved.', 'verification.errorTitle': 'Could not submit document',
    'fulfillment.instant': 'Available now', 'fulfillment.appointment_required': 'Booking required', 'fulfillment.scheduled_event': 'Scheduled event',
    'error.studentNotVerified': 'You need an approved verification before claiming a treat.', 'error.claimLimit': 'You can claim one treat every 24 hours.', 'error.soldOut': 'These treats ran out in the meantime.', 'error.campaignUnavailable': 'This treat is not available right now.', 'error.genericClaim': 'We could not claim this treat. Try again.', 'error.generic': 'Something went wrong. Try again.',
    'category.food-drink': 'Food & drink', 'category.cinema': 'Cinema', 'category.hair-grooming': 'Hair & grooming', 'category.beauty': 'Beauty & personal care', 'category.fitness': 'Fitness & sports', 'category.entertainment': 'Entertainment', 'category.activities': 'Activities', 'category.education': 'Education', 'category.mobility': 'Mobility', 'category.other': 'Other',
    'catalog.cappuccino.name': 'Cappuccino', 'catalog.cappuccino.description': 'A good coffee, from someone who wants to treat you.', 'catalog.cappuccino.redemption_instructions': 'Show your CINSTE code at the counter.', 'catalog.movie_ticket.name': 'Movie ticket', 'catalog.movie_ticket.description': 'A ticket for a selected screening.', 'catalog.movie_ticket.redemption_instructions': 'Show your QR code at the entrance.', 'catalog.student_haircut.name': 'Student haircut', 'catalog.student_haircut.description': 'A haircut for students.', 'catalog.student_haircut.redemption_instructions': 'Book by phone and mention CINSTE.',
  },
  tr: {
    'common.loading': 'Yükleniyor…', 'common.back': 'Geri', 'common.retry': 'Tekrar dene', 'common.cancel': 'İptal', 'common.confirm': 'Onayla', 'common.free': 'ÜCRETSİZ',
    'auth.login.title': 'Tekrar hoş geldin', 'auth.login.subtitle': 'Bugün kimin ısmarladığını görmek için giriş yap.', 'auth.login.submit': 'Giriş yap', 'auth.login.submitting': 'Giriş yapılıyor…', 'auth.login.noAccount': 'Hesabın yok mu? Oluştur', 'auth.login.errorTitle': 'Giriş yapılamadı',
    'auth.register.title': 'CINSTE’ye katıl', 'auth.register.subtitle': 'Hesap açmak seni otomatik olarak öğrenci doğrulamaz.', 'auth.register.submit': 'Hesap oluştur', 'auth.register.submitting': 'Hesap oluşturuluyor…', 'auth.register.hasAccount': 'Zaten hesabın var mı? Giriş yap', 'auth.register.errorTitle': 'Hesap oluşturulamadı', 'auth.register.confirmEmailTitle': 'E-postanı kontrol et', 'auth.register.confirmEmail': 'Giriş yapmadan önce e-posta adresini onayla.',
    'auth.email': 'E-posta', 'auth.password': 'Şifre', 'auth.fullName': 'Ad soyad',
    'tabs.discover': 'Keşfet', 'tabs.myCinste': 'İkramlarım', 'tabs.profile': 'Profil',
    'discover.kicker': 'SANA ÖZEL', 'discover.title': 'Bugün kim ısmarlıyor?', 'discover.subtitle': 'Doğrulanmış öğrenciler için güzel deneyimler.', 'discover.loading': 'Bugünün ikramları aranıyor…', 'discover.all': 'Tümü', 'discover.available_zero': 'Şu an ikram yok', 'discover.available_one': '{{formattedCount}} adet var', 'discover.available_two': '{{formattedCount}} adet var', 'discover.available_few': '{{formattedCount}} adet var', 'discover.available_many': '{{formattedCount}} adet var', 'discover.available_other': '{{formattedCount}} adet var', 'discover.availabilityFree': '{{availability}} · {{free}}', 'discover.emptyTitle': 'Şu an ikram yok.', 'discover.emptyCopy': 'Yakında tekrar gel. Yenilerini hazırlıyoruz.',
    'offer.notFound': 'Bu ikram bulunamadı', 'offer.partner': 'İş ortağı', 'offer.event': 'Etkinlik: {{date}}', 'offer.bookBefore': 'Gitmeden önce rezervasyon yap.', 'offer.openBooking': 'Rezervasyonu aç', 'offer.reserveNote': 'Her 24 saatte bir ikram alabilirsin.', 'offer.claim': 'İkramı al', 'offer.claiming': 'Alınıyor…', 'offer.claimErrorTitle': 'İkram alınamadı',
    'claim.notFound': 'Bu ikram bulunamadı', 'claim.active': 'Aktif', 'claim.redeemed': 'Kullanıldı', 'claim.expired': 'Süresi doldu', 'claim.cancelled': 'İptal edildi', 'claim.showPartnerQr': 'Bu kodu iş ortağına göster', 'claim.inactive': 'Bu ikram artık kullanılamaz.', 'claim.expiresAt': 'Geçerlilik: {{date}}', 'claim.showManualCode': 'Manuel koda mı ihtiyacın var?', 'claim.hideManualCode': 'Manuel kodu gizle',
    'myCinste.loading': 'İkramların hazırlanıyor…', 'myCinste.active': 'Aktif', 'myCinste.history': 'Geçmiş', 'myCinste.noActive': 'Şu an aktif bir ikramın yok.', 'myCinste.noHistory': 'Kullandığın ve süresi dolan ikramlar burada görünür.',
    'profile.title': 'Profilim', 'profile.howItWorks': 'Nasıl çalışır?', 'profile.howItWorksCopy': 'İkram, birinin sunduğu deneyimdir. Doğrulandıktan sonra birini alabilir ve iş ortağında QR kodunla kullanabilirsin.', 'profile.logout': 'Çıkış yap', 'profile.language': 'Dil', 'profile.chooseLanguage': 'Dil seç', 'profile.languageHint': 'Dili istediğin zaman değiştirebilirsin.',
    'verification.verified': 'Doğrulanmış öğrenci', 'verification.pending': 'Doğrulama bekliyor', 'verification.rejected': 'Doğrulama reddedildi', 'verification.unverified': 'Henüz doğrulanmadı', 'verification.submitDocument': 'Belge gönder', 'verification.pendingButton': 'Doğrulama sürüyor', 'verification.approvedTitle': 'Doğrulandın', 'verification.approvedCopy': 'Şimdi uygun bir ikram alabilirsin.', 'verification.pendingTitle': 'Doğrulama sürüyor', 'verification.pendingCopy': 'Belgen inceleniyor. Durum değiştiğinde bu ekranda göreceksin.', 'verification.title': 'Öğrenci olarak doğrulan', 'verification.subtitle': 'Hesabın ve doğrulaman ayrıdır. Belgen yalnızca CINSTE ekibine gider.', 'verification.university': 'Üniversite', 'verification.faculty': 'Fakülte (isteğe bağlı)', 'verification.document': 'Öğrenci belgesi', 'verification.documentHint': 'PDF, JPG veya PNG · en fazla 5 MB', 'verification.pickDocument': 'Belge seç', 'verification.pickPhoto': 'Fotoğraf seç', 'verification.submit': 'Doğrulama için gönder', 'verification.submitting': 'Gönderiliyor…', 'verification.invalidDocumentTitle': 'Geçersiz belge', 'verification.invalidDocument': '5 MB’dan küçük PDF, JPG veya PNG seç.', 'verification.missingTitle': 'Eksik bilgi var', 'verification.missing': 'Adını, üniversiteni ve belgeni ekle.', 'verification.successTitle': 'İncelemeye gönderildi', 'verification.success': 'Belgen onaylandığında bu ekranda göreceksin.', 'verification.errorTitle': 'Belge gönderilemedi',
    'fulfillment.instant': 'Şimdi kullanılabilir', 'fulfillment.appointment_required': 'Rezervasyon gerekli', 'fulfillment.scheduled_event': 'Planlanmış etkinlik',
    'error.studentNotVerified': 'İkram almadan önce doğrulamanın onaylanması gerekiyor.', 'error.claimLimit': 'Her 24 saatte bir ikram alabilirsin.', 'error.soldOut': 'İkramlar bu arada tükendi.', 'error.campaignUnavailable': 'Bu ikram şu an uygun değil.', 'error.genericClaim': 'Bu ikram alınamadı. Tekrar dene.', 'error.generic': 'Bir sorun oluştu. Tekrar dene.',
    'category.food-drink': 'Yeme içme', 'category.cinema': 'Sinema', 'category.hair-grooming': 'Saç ve bakım', 'category.beauty': 'Güzellik ve kişisel bakım', 'category.fitness': 'Fitness ve spor', 'category.entertainment': 'Eğlence', 'category.activities': 'Aktiviteler', 'category.education': 'Eğitim', 'category.mobility': 'Ulaşım', 'category.other': 'Diğer',
    'catalog.cappuccino.name': 'Cappuccino', 'catalog.cappuccino.description': 'Birinin ikramı olan güzel bir kahve.', 'catalog.cappuccino.redemption_instructions': 'Barda CINSTE kodunu göster.', 'catalog.movie_ticket.name': 'Sinema bileti', 'catalog.movie_ticket.description': 'Seçili bir gösterim için bilet.', 'catalog.movie_ticket.redemption_instructions': 'Girişte QR kodunu göster.', 'catalog.student_haircut.name': 'Öğrenci saç kesimi', 'catalog.student_haircut.description': 'Öğrenciler için saç kesimi.', 'catalog.student_haircut.redemption_instructions': 'Telefonla randevu al ve CINSTE’den bahset.',
  },
  ar: {
    'common.loading': 'جارٍ التحميل…', 'common.back': 'رجوع', 'common.retry': 'حاول مرة أخرى', 'common.cancel': 'إلغاء', 'common.confirm': 'تأكيد', 'common.free': 'مجانًا',
    'auth.login.title': 'أهلًا بعودتك', 'auth.login.subtitle': 'سجّل الدخول لترى من يقدم الضيافة اليوم.', 'auth.login.submit': 'تسجيل الدخول', 'auth.login.submitting': 'جارٍ تسجيل الدخول…', 'auth.login.noAccount': 'ليس لديك حساب؟ أنشئ حسابًا', 'auth.login.errorTitle': 'تعذر تسجيل الدخول',
    'auth.register.title': 'انضم إلى CINSTE', 'auth.register.subtitle': 'وجود حساب لا يعني التحقق منك كطالب تلقائيًا.', 'auth.register.submit': 'إنشاء حساب', 'auth.register.submitting': 'جارٍ إنشاء الحساب…', 'auth.register.hasAccount': 'لديك حساب بالفعل؟ سجّل الدخول', 'auth.register.errorTitle': 'تعذر إنشاء الحساب', 'auth.register.confirmEmailTitle': 'تحقق من بريدك', 'auth.register.confirmEmail': 'أكد عنوان بريدك الإلكتروني قبل تسجيل الدخول.',
    'auth.email': 'البريد الإلكتروني', 'auth.password': 'كلمة المرور', 'auth.fullName': 'الاسم الكامل',
    'tabs.discover': 'استكشف', 'tabs.myCinste': 'ضيافاتي', 'tabs.profile': 'الملف الشخصي',
    'discover.kicker': 'لك', 'discover.title': 'من يقدم الضيافة اليوم؟', 'discover.subtitle': 'تجارب جميلة مقدمة للطلاب الذين تم التحقق منهم.', 'discover.loading': 'نبحث عن ضيافات اليوم…', 'discover.all': 'الكل', 'discover.available_zero': 'لا توجد ضيافات متاحة', 'discover.available_one': 'ضيافة واحدة متاحة', 'discover.available_two': 'ضيافتان متاحتان', 'discover.available_few': '{{formattedCount}} ضيافات متاحة', 'discover.available_many': '{{formattedCount}} ضيافة متاحة', 'discover.available_other': '{{formattedCount}} ضيافة متاحة', 'discover.availabilityFree': '{{free}} · {{availability}}', 'discover.emptyTitle': 'لا توجد ضيافات متاحة الآن.', 'discover.emptyCopy': 'عد قريبًا، فنحن نجهز المزيد.',
    'offer.notFound': 'لم نعثر على هذه الضيافة', 'offer.partner': 'الشريك', 'offer.event': 'الفعالية: {{date}}', 'offer.bookBefore': 'احجز قبل الذهاب.', 'offer.openBooking': 'فتح الحجز', 'offer.reserveNote': 'يمكنك الحصول على ضيافة واحدة كل 24 ساعة.', 'offer.claim': 'احصل عليها', 'offer.claiming': 'جارٍ الحجز…', 'offer.claimErrorTitle': 'تعذر حجز الضيافة',
    'claim.notFound': 'لم نعثر على هذه الضيافة', 'claim.active': 'نشطة', 'claim.redeemed': 'استُخدمت', 'claim.expired': 'منتهية', 'claim.cancelled': 'ملغاة', 'claim.showPartnerQr': 'اعرض هذا الرمز على الشريك', 'claim.inactive': 'لم تعد هذه الضيافة قابلة للاستخدام.', 'claim.expiresAt': 'صالحة حتى {{date}}', 'claim.showManualCode': 'هل تحتاج إلى رمز يدوي؟', 'claim.hideManualCode': 'إخفاء الرمز اليدوي',
    'myCinste.loading': 'نجمع ضيافاتك…', 'myCinste.active': 'نشطة', 'myCinste.history': 'السجل', 'myCinste.noActive': 'ليس لديك ضيافة نشطة الآن.', 'myCinste.noHistory': 'ستظهر هنا الضيافات المستخدمة والمنتهية.',
    'profile.title': 'ملفي الشخصي', 'profile.howItWorks': 'كيف تعمل', 'profile.howItWorksCopy': 'الضيافة تجربة يقدمها شخص ما. بعد التحقق، يمكنك طلب واحدة واستخدام رمز QR لدى الشريك.', 'profile.logout': 'تسجيل الخروج', 'profile.language': 'اللغة', 'profile.chooseLanguage': 'اختر اللغة', 'profile.languageHint': 'يمكنك تغيير اللغة في أي وقت.',
    'verification.verified': 'طالب تم التحقق منه', 'verification.pending': 'التحقق قيد المراجعة', 'verification.rejected': 'تم رفض التحقق', 'verification.unverified': 'لم يتم التحقق بعد', 'verification.submitDocument': 'أرسل المستند', 'verification.pendingButton': 'التحقق قيد التنفيذ', 'verification.approvedTitle': 'تم التحقق منك', 'verification.approvedCopy': 'يمكنك الآن طلب ضيافة متاحة.', 'verification.pendingTitle': 'التحقق قيد المراجعة', 'verification.pendingCopy': 'مستندك قيد المراجعة. سنحدّث هذه الشاشة عند تغيير الحالة.', 'verification.title': 'تحقق كطالب', 'verification.subtitle': 'الحساب والتحقق أمران منفصلان. يصل مستندك إلى فريق CINSTE فقط.', 'verification.university': 'الجامعة', 'verification.faculty': 'الكلية (اختياري)', 'verification.document': 'مستند الطالب', 'verification.documentHint': 'PDF أو JPG أو PNG · بحد أقصى 5 ميغابايت', 'verification.pickDocument': 'اختر مستندًا', 'verification.pickPhoto': 'اختر صورة', 'verification.submit': 'إرسال للتحقق', 'verification.submitting': 'جارٍ الإرسال…', 'verification.invalidDocumentTitle': 'مستند غير صالح', 'verification.invalidDocument': 'اختر PDF أو JPG أو PNG أصغر من 5 ميغابايت.', 'verification.missingTitle': 'هناك معلومات ناقصة', 'verification.missing': 'أضف اسمك وجامعتك ومستندك.', 'verification.successTitle': 'تم الإرسال للمراجعة', 'verification.success': 'سنحدّث هذه الشاشة عند اعتماد مستندك.', 'verification.errorTitle': 'تعذر إرسال المستند',
    'fulfillment.instant': 'متاحة الآن', 'fulfillment.appointment_required': 'الحجز مطلوب', 'fulfillment.scheduled_event': 'فعالية مجدولة',
    'error.studentNotVerified': 'تحتاج إلى تحقق معتمد قبل طلب ضيافة.', 'error.claimLimit': 'يمكنك طلب ضيافة واحدة كل 24 ساعة.', 'error.soldOut': 'نفدت الضيافات في هذه الأثناء.', 'error.campaignUnavailable': 'هذه الضيافة غير متاحة الآن.', 'error.genericClaim': 'تعذر طلب هذه الضيافة. حاول مرة أخرى.', 'error.generic': 'حدث خطأ ما. حاول مرة أخرى.',
    'category.food-drink': 'طعام وشراب', 'category.cinema': 'سينما', 'category.hair-grooming': 'الشعر والعناية', 'category.beauty': 'الجمال والعناية الشخصية', 'category.fitness': 'اللياقة والرياضة', 'category.entertainment': 'ترفيه', 'category.activities': 'أنشطة', 'category.education': 'تعليم', 'category.mobility': 'تنقل', 'category.other': 'أخرى',
    'catalog.cappuccino.name': 'كابتشينو', 'catalog.cappuccino.description': 'قهوة رائعة يقدمها لك شخص ما.', 'catalog.cappuccino.redemption_instructions': 'اعرض رمز CINSTE عند البار.', 'catalog.movie_ticket.name': 'تذكرة سينما', 'catalog.movie_ticket.description': 'تذكرة لعرض مختار.', 'catalog.movie_ticket.redemption_instructions': 'اعرض رمز QR عند المدخل.', 'catalog.student_haircut.name': 'قصة شعر للطالب', 'catalog.student_haircut.description': 'قصة شعر للطلاب.', 'catalog.student_haircut.redemption_instructions': 'احجز عبر الهاتف واذكر CINSTE.',
  },
} as const;

const verificationResubmissionTranslations = {
  ro: {
    'verification.rejectedTitle': 'Verificarea a fost respinsă',
    'verification.rejectedCopy': 'Poți trimite un document nou pentru o nouă verificare.',
    'verification.rejectionReason': 'Motivul respingerii',
    'verification.resubmit': 'Trimite un document nou',
  },
  en: {
    'verification.rejectedTitle': 'Your verification was rejected',
    'verification.rejectedCopy': 'You can send a replacement document for another review.',
    'verification.rejectionReason': 'Reason for rejection',
    'verification.resubmit': 'Submit a replacement document',
  },
  tr: {
    'verification.rejectedTitle': 'Doğrulaman reddedildi',
    'verification.rejectedCopy': 'Yeni bir inceleme için yeni bir belge gönderebilirsin.',
    'verification.rejectionReason': 'Red nedeni',
    'verification.resubmit': 'Yeni belge gönder',
  },
  ar: {
    'verification.rejectedTitle': 'تم رفض التحقق',
    'verification.rejectedCopy': 'يمكنك إرسال مستند بديل لمراجعة جديدة.',
    'verification.rejectionReason': 'سبب الرفض',
    'verification.resubmit': 'أرسل مستندًا بديلًا',
  },
} as const;

const mobileBoundaryTranslations = {
  ro: {
    'mobileBoundary.title': 'Acest cont folosește CINSTE pe web',
    'mobileBoundary.partner': 'Operațiunile de partener sunt disponibile în spațiul Partner CINSTE de pe web.',
    'mobileBoundary.giver': 'A face cinste și finanțarea experiențelor sunt disponibile pe CINSTE web.',
    'mobileBoundary.admin': 'Administrarea CINSTE este disponibilă în spațiul Admin de pe web.',
    'mobileBoundary.unknown': 'Nu am putut confirma accesul de student pentru acest cont. Încearcă din nou sau intră cu un cont de student.',
    'mobileBoundary.logout': 'Ieși din cont',
  },
  en: {
    'mobileBoundary.title': 'This account uses CINSTE on the web',
    'mobileBoundary.partner': 'Partner operations are available in the CINSTE Partner workspace on the web.',
    'mobileBoundary.giver': 'Treating someone and funding experiences are available on CINSTE web.',
    'mobileBoundary.admin': 'CINSTE administration is available in the Admin workspace on the web.',
    'mobileBoundary.unknown': 'We could not confirm student access for this account. Try again or sign in with a student account.',
    'mobileBoundary.logout': 'Log out',
  },
  tr: {
    'mobileBoundary.title': 'Bu hesap CINSTE web kullanır',
    'mobileBoundary.partner': 'İş ortağı işlemleri webdeki CINSTE Partner alanında kullanılabilir.',
    'mobileBoundary.giver': 'Birine ısmarlamak ve deneyimleri finanse etmek CINSTE webde kullanılabilir.',
    'mobileBoundary.admin': 'CINSTE yönetimi webdeki Admin alanında kullanılabilir.',
    'mobileBoundary.unknown': 'Bu hesap için öğrenci erişimini doğrulayamadık. Tekrar dene veya öğrenci hesabıyla giriş yap.',
    'mobileBoundary.logout': 'Çıkış yap',
  },
  ar: {
    'mobileBoundary.title': 'يستخدم هذا الحساب CINSTE على الويب',
    'mobileBoundary.partner': 'عمليات الشركاء متاحة في مساحة CINSTE Partner على الويب.',
    'mobileBoundary.giver': 'تقديم الضيافة وتمويل التجارب متاحان عبر CINSTE على الويب.',
    'mobileBoundary.admin': 'إدارة CINSTE متاحة في مساحة Admin على الويب.',
    'mobileBoundary.unknown': 'تعذر تأكيد وصول الطالب لهذا الحساب. حاول مرة أخرى أو سجّل الدخول بحساب طالب.',
    'mobileBoundary.logout': 'تسجيل الخروج',
  },
} as const;

const workspaceTranslations = {
  ro: { 'workspace.title': 'Alege spațiul CINSTE', 'workspace.copy': 'Alege o zonă disponibilă pentru acest cont.', 'workspace.open': 'Deschide', 'workspace.student': 'Student', 'workspace.giver': 'Giver', 'workspace.partner': 'Partener', 'workspace.organization': 'Organizație', 'workspace.logout': 'Ieși din cont', 'giver.title': 'Spațiul Giver', 'giver.entryTitle': 'În curând', 'giver.entryCopy': 'Pregătim aici experiența Giver. Nu există încă funcții de finanțare în aplicație.', 'giver.logout': 'Ieși din cont' },
  en: { 'workspace.title': 'Choose a CINSTE workspace', 'workspace.copy': 'Choose an available space for this account.', 'workspace.open': 'Open', 'workspace.student': 'Student', 'workspace.giver': 'Giver', 'workspace.partner': 'Partner', 'workspace.organization': 'Organization', 'workspace.logout': 'Log out', 'giver.title': 'Giver workspace', 'giver.entryTitle': 'Coming soon', 'giver.entryCopy': 'The Giver experience is being prepared here. Funding is not available in the app yet.', 'giver.logout': 'Log out' },
  tr: { 'workspace.title': 'Bir CINSTE alanı seç', 'workspace.copy': 'Bu hesap için kullanılabilir bir alan seç.', 'workspace.open': 'Aç', 'workspace.student': 'Öğrenci', 'workspace.giver': 'Giver', 'workspace.partner': 'İş ortağı', 'workspace.organization': 'Kuruluş', 'workspace.logout': 'Çıkış yap', 'giver.title': 'Giver alanı', 'giver.entryTitle': 'Yakında', 'giver.entryCopy': 'Giver deneyimini burada hazırlıyoruz. Finanse etme özellikleri henüz uygulamada kullanılamıyor.', 'giver.logout': 'Çıkış yap' },
  ar: { 'workspace.title': 'اختر مساحة CINSTE', 'workspace.copy': 'اختر مساحة متاحة لهذا الحساب.', 'workspace.open': 'فتح', 'workspace.student': 'طالب', 'workspace.giver': 'مانح', 'workspace.partner': 'شريك', 'workspace.organization': 'منظمة', 'workspace.logout': 'تسجيل الخروج', 'giver.title': 'مساحة المانح', 'giver.entryTitle': 'قريبًا', 'giver.entryCopy': 'نجهز تجربة المانح هنا. لا تتوفر ميزات التمويل في التطبيق بعد.', 'giver.logout': 'تسجيل الخروج' },
} as const;

const nativeGiverReadTranslations = {
  ro: { 'giver.catalog': 'Oferte', 'giver.outcomes': 'Cinstile mele', 'giver.loading': 'Se încarcă…', 'giver.errorTitle': 'Nu am putut încărca datele', 'giver.errorCopy': 'Încearcă din nou. Nu s-a făcut nicio acțiune.', 'giver.emptyCatalog': 'Nu există oferte active', 'giver.emptyCatalogCopy': 'Revino în curând pentru experiențe noi.', 'giver.emptyOutcomes': 'Nu ai încă rezultate', 'giver.emptyOutcomesCopy': 'Rezultatele finanțărilor tale vor apărea aici.', 'giver.unavailable': 'Indisponibil', 'giver.offerUnavailable': 'Oferta nu mai este disponibilă', 'giver.offerUnavailableCopy': 'Oferta poate fi inactivă sau nu mai este vizibilă.', 'giver.fundedOne': '{{count}} experiență finanțată', 'giver.fundedMany': '{{count}} experiențe finanțate', 'giver.reserved': 'Rezervate', 'giver.redeemed': 'Folosite', 'giver.recordedAvailable': 'Disponibile înregistrate', 'giver.available': 'Disponibile acum', 'giver.outcome.available': 'Rezultat disponibil', 'giver.outcome.privacy_suppressed': 'Detalii protejate', 'giver.outcome.unavailable': 'Rezultat indisponibil', 'giver.outcomeCopy.privacy_suppressed': 'Detaliile de activitate sunt ascunse pentru protejarea confidențialității.', 'giver.outcomeCopy.unavailable': 'Detaliile rezultatului nu pot fi afișate acum.' },
  en: { 'giver.catalog': 'Offers', 'giver.outcomes': 'My Giving', 'giver.loading': 'Loading…', 'giver.errorTitle': 'We could not load this', 'giver.errorCopy': 'Try again. No action was taken.', 'giver.emptyCatalog': 'No active offers', 'giver.emptyCatalogCopy': 'Come back soon for new experiences.', 'giver.emptyOutcomes': 'No outcomes yet', 'giver.emptyOutcomesCopy': 'Your funded outcomes will appear here.', 'giver.unavailable': 'Unavailable', 'giver.offerUnavailable': 'Offer unavailable', 'giver.offerUnavailableCopy': 'This offer may be inactive or no longer visible.', 'giver.fundedOne': '{{count}} funded experience', 'giver.fundedMany': '{{count}} funded experiences', 'giver.reserved': 'Reserved', 'giver.redeemed': 'Redeemed', 'giver.recordedAvailable': 'Recorded available', 'giver.available': 'Available now', 'giver.outcome.available': 'Outcome available', 'giver.outcome.privacy_suppressed': 'Details protected', 'giver.outcome.unavailable': 'Outcome unavailable', 'giver.outcomeCopy.privacy_suppressed': 'Activity details are hidden to protect privacy.', 'giver.outcomeCopy.unavailable': 'Outcome details cannot be shown right now.' },
  tr: { 'giver.catalog': 'Teklifler', 'giver.outcomes': 'Bağışlarım', 'giver.loading': 'Yükleniyor…', 'giver.errorTitle': 'Veriler yüklenemedi', 'giver.errorCopy': 'Tekrar dene. Hiçbir işlem yapılmadı.', 'giver.emptyCatalog': 'Aktif teklif yok', 'giver.emptyCatalogCopy': 'Yeni deneyimler için yakında tekrar bak.', 'giver.emptyOutcomes': 'Henüz sonuç yok', 'giver.emptyOutcomesCopy': 'Finanse ettiğin sonuçlar burada görünecek.', 'giver.unavailable': 'Kullanılamıyor', 'giver.offerUnavailable': 'Teklif kullanılamıyor', 'giver.offerUnavailableCopy': 'Bu teklif pasif veya artık görünür değil.', 'giver.fundedOne': '{{count}} finanse edilen deneyim', 'giver.fundedMany': '{{count}} finanse edilen deneyim', 'giver.reserved': 'Ayrılan', 'giver.redeemed': 'Kullanılan', 'giver.recordedAvailable': 'Kayıtlı kullanılabilir', 'giver.available': 'Şimdi kullanılabilir', 'giver.outcome.available': 'Sonuç kullanılabilir', 'giver.outcome.privacy_suppressed': 'Ayrıntılar korumalı', 'giver.outcome.unavailable': 'Sonuç kullanılamıyor', 'giver.outcomeCopy.privacy_suppressed': 'Etkinlik ayrıntıları gizlilik için gizlendi.', 'giver.outcomeCopy.unavailable': 'Sonuç ayrıntıları şu anda gösterilemiyor.' },
  ar: { 'giver.catalog': 'العروض', 'giver.outcomes': 'عطائي', 'giver.loading': 'جارٍ التحميل…', 'giver.errorTitle': 'تعذر تحميل البيانات', 'giver.errorCopy': 'حاول مرة أخرى. لم يُنفذ أي إجراء.', 'giver.emptyCatalog': 'لا توجد عروض نشطة', 'giver.emptyCatalogCopy': 'عد قريبًا لرؤية تجارب جديدة.', 'giver.emptyOutcomes': 'لا توجد نتائج بعد', 'giver.emptyOutcomesCopy': 'ستظهر نتائج تمويلك هنا.', 'giver.unavailable': 'غير متاح', 'giver.offerUnavailable': 'العرض غير متاح', 'giver.offerUnavailableCopy': 'قد يكون العرض غير نشط أو لم يعد ظاهرًا.', 'giver.fundedOne': 'تجربة ممولة واحدة', 'giver.fundedMany': '{{count}} تجارب ممولة', 'giver.reserved': 'محجوز', 'giver.redeemed': 'مستخدم', 'giver.recordedAvailable': 'المتاح المسجل', 'giver.available': 'متاح الآن', 'giver.outcome.available': 'النتيجة متاحة', 'giver.outcome.privacy_suppressed': 'التفاصيل محمية', 'giver.outcome.unavailable': 'النتيجة غير متاحة', 'giver.outcomeCopy.privacy_suppressed': 'تم إخفاء تفاصيل النشاط لحماية الخصوصية.', 'giver.outcomeCopy.unavailable': 'لا يمكن عرض تفاصيل النتيجة الآن.' },
} as const;

const nativeGiverShellTranslations = {
  ro: { 'giver.account': 'Cont', 'giver.accountCopy': 'Gestionează limba și sesiunea contului tău.', 'giver.catalogIntro': 'Descoperă experiențe pe care le poți susține.', 'giver.offerTitle': 'Detalii ofertă' },
  en: { 'giver.account': 'Account', 'giver.accountCopy': 'Manage your account language and session.', 'giver.catalogIntro': 'Discover experiences you can support.', 'giver.offerTitle': 'Offer details' },
  tr: { 'giver.account': 'Hesap', 'giver.accountCopy': 'Hesap dilini ve oturumunu yönet.', 'giver.catalogIntro': 'Destekleyebileceğin deneyimleri keşfet.', 'giver.offerTitle': 'Teklif ayrıntıları' },
  ar: { 'giver.account': 'الحساب', 'giver.accountCopy': 'أدر لغة حسابك وجلستك.', 'giver.catalogIntro': 'اكتشف التجارب التي يمكنك دعمها.', 'giver.offerTitle': 'تفاصيل العرض' },
} as const;

const impactTranslations = {
  ro: { 'tabs.impact': 'Impact', 'impact.loading': 'Încărcăm Impact…', 'impact.title': 'Impact', 'impact.open': 'Fă binele să meargă mai departe.', 'impact.due': 'Ai o contribuție de finalizat înainte de următoarea cinste Community.', 'impact.contributions': 'contribuții verificate', 'impact.minutes': 'minute verificate', 'impact.organizations': 'organizații ajutate', 'impact.active': 'Participările mele', 'impact.history': 'Istoricul participărilor', 'impact.explore': 'Descoperă oportunități', 'impact.emptyTitle': 'Nu sunt oportunități acum.', 'impact.emptyCopy': 'Revino curând pentru noi moduri de a ajuta.', 'impact.remote': 'Flexibil / remote', 'impact.slots': '{{count}} locuri', 'impact.notFound': 'Oportunitatea nu mai este disponibilă', 'impact.participationUnavailable': 'Detaliile oportunității nu sunt disponibile', 'impact.organizationUnavailable': 'Participarea ta este în continuare înregistrată.', 'impact.errorTitle': 'Nu putem încărca Impact acum', 'impact.errorCopy': 'Datele tale nu au fost încărcate. Încearcă din nou.', 'impact.actionError': 'Acțiunea nu a reușit', 'impact.actionErrorCopy': 'Încearcă din nou.', 'impact.historyOnly': 'Istoricul și contribuțiile tale rămân vizibile în timp ce verificarea este în curs. Participarea la oportunități noi este blocată.', 'impact.verification': 'Verificare student', 'impact.dispute': 'Contestă', 'impact.disputeTitle': 'Solicită revizuirea rezultatului', 'impact.disputePlaceholder': 'Spune de ce trebuie revizuit acest rezultat', 'impact.submitDispute': 'Trimite contestația', 'impact.requestReview': 'Solicită revizuire Admin', 'impact.reviewRequested': 'Revizuirea Admin a fost solicitată.', 'impact.reviewRequestedTitle': 'Cerere trimisă', 'impact.reviewRequestedCopy': 'Admin va vedea solicitarea ta de revizuire.', 'impact.join': 'Participă', 'impact.cancel': 'Anulează participarea', 'impact.starts': 'Începe: {{date}}', 'impact.dueDate': 'Termen: {{date}}', 'impact.status.joined': 'Înscris', 'impact.status.overdue': 'În așteptare', 'impact.status.completed': 'Finalizat', 'impact.status.cancelled': 'Anulat', 'impact.status.cancelled_by_organization': 'Anulat de organizație', 'impact.status.no_show': 'Neprezentare', 'impact.status.excused': 'Scutit', 'impact.status.expired_incomplete': 'Expirat incomplet', 'impact.status.disputed': 'În dispută' },
  en: { 'tabs.impact': 'Impact', 'impact.loading': 'Loading Impact…', 'impact.title': 'Impact', 'impact.open': 'Keep generosity moving forward.', 'impact.due': 'Complete a contribution before your next Community treat.', 'impact.contributions': 'verified contributions', 'impact.minutes': 'verified minutes', 'impact.organizations': 'organizations helped', 'impact.active': 'My participations', 'impact.history': 'Participation history', 'impact.explore': 'Explore opportunities', 'impact.emptyTitle': 'No opportunities yet.', 'impact.emptyCopy': 'Check back soon for ways to help.', 'impact.remote': 'Flexible / remote', 'impact.slots': '{{count}} places', 'impact.notFound': 'This opportunity is no longer available', 'impact.participationUnavailable': 'Opportunity details are unavailable', 'impact.organizationUnavailable': 'Your participation is still recorded.', 'impact.errorTitle': 'Impact could not load', 'impact.errorCopy': 'Your Impact data was not loaded. Try again.', 'impact.actionError': 'Action could not be completed', 'impact.actionErrorCopy': 'Try again.', 'impact.historyOnly': 'Your history and contributions stay visible while verification is pending. Joining new opportunities is unavailable.', 'impact.verification': 'Student verification', 'impact.dispute': 'Dispute outcome', 'impact.disputeTitle': 'Request an outcome review', 'impact.disputePlaceholder': 'Tell us why this outcome should be reviewed', 'impact.submitDispute': 'Submit dispute', 'impact.requestReview': 'Request Admin review', 'impact.reviewRequested': 'Admin review requested.', 'impact.reviewRequestedTitle': 'Request sent', 'impact.reviewRequestedCopy': 'An Admin can now see your review request.', 'impact.join': 'Join', 'impact.cancel': 'Cancel participation', 'impact.starts': 'Starts: {{date}}', 'impact.dueDate': 'Deadline: {{date}}', 'impact.status.joined': 'Joined', 'impact.status.overdue': 'Awaiting review', 'impact.status.completed': 'Completed', 'impact.status.cancelled': 'Cancelled', 'impact.status.cancelled_by_organization': 'Cancelled by organization', 'impact.status.no_show': 'No-show', 'impact.status.excused': 'Excused', 'impact.status.expired_incomplete': 'Expired incomplete', 'impact.status.disputed': 'Disputed' },
  tr: { 'tabs.impact': 'Etki', 'impact.loading': 'Etki yükleniyor…', 'impact.title': 'Etki', 'impact.open': 'İyiliği ileri taşı.', 'impact.due': 'Bir sonraki Community ikramından önce bir katkıyı tamamla.', 'impact.contributions': 'doğrulanmış katkı', 'impact.minutes': 'doğrulanmış dakika', 'impact.organizations': 'desteklenen kuruluş', 'impact.active': 'Katılımlarım', 'impact.history': 'Katılım geçmişi', 'impact.explore': 'Fırsatları keşfet', 'impact.emptyTitle': 'Henüz fırsat yok.', 'impact.emptyCopy': 'Yardım etmenin yolları için yakında tekrar bak.', 'impact.remote': 'Esnek / uzaktan', 'impact.slots': '{{count}} yer', 'impact.notFound': 'Bu fırsat artık uygun değil', 'impact.participationUnavailable': 'Fırsat ayrıntıları kullanılamıyor', 'impact.organizationUnavailable': 'Katılımın hâlâ kayıtlı.', 'impact.errorTitle': 'Etki yüklenemedi', 'impact.errorCopy': 'Etki verilerin yüklenmedi. Tekrar dene.', 'impact.actionError': 'İşlem tamamlanamadı', 'impact.actionErrorCopy': 'Tekrar dene.', 'impact.historyOnly': 'Doğrulama beklerken geçmişin ve katkıların görünür kalır. Yeni fırsatlara katılım kullanılamaz.', 'impact.verification': 'Öğrenci doğrulama', 'impact.dispute': 'Sonuca itiraz et', 'impact.disputeTitle': 'Sonuç incelemesi iste', 'impact.disputePlaceholder': 'Bu sonucun neden incelenmesi gerektiğini yaz', 'impact.submitDispute': 'İtirazı gönder', 'impact.requestReview': 'Admin incelemesi iste', 'impact.reviewRequested': 'Admin incelemesi istendi.', 'impact.reviewRequestedTitle': 'İstek gönderildi', 'impact.reviewRequestedCopy': 'Bir Admin artık inceleme isteğini görebilir.', 'impact.join': 'Katıl', 'impact.cancel': 'Katılımı iptal et', 'impact.starts': 'Başlangıç: {{date}}', 'impact.dueDate': 'Son tarih: {{date}}', 'impact.status.joined': 'Katıldı', 'impact.status.overdue': 'İnceleme bekliyor', 'impact.status.completed': 'Tamamlandı', 'impact.status.cancelled': 'İptal edildi', 'impact.status.cancelled_by_organization': 'Kuruluş iptal etti', 'impact.status.no_show': 'Katılmadı', 'impact.status.excused': 'Mazeretli', 'impact.status.expired_incomplete': 'Süresi doldu', 'impact.status.disputed': 'İtirazlı' },
  ar: { 'tabs.impact': 'الأثر', 'impact.loading': 'جارٍ تحميل الأثر…', 'impact.title': 'الأثر', 'impact.open': 'دع الكرم يستمر.', 'impact.due': 'أكمل مساهمة قبل هديتك المجتمعية التالية.', 'impact.contributions': 'مساهمات موثقة', 'impact.minutes': 'دقائق موثقة', 'impact.organizations': 'منظمات تمت مساعدتها', 'impact.active': 'مشاركاتي', 'impact.history': 'سجل المشاركات', 'impact.explore': 'استكشف الفرص', 'impact.emptyTitle': 'لا توجد فرص بعد.', 'impact.emptyCopy': 'عد قريبًا لطرق جديدة للمساعدة.', 'impact.remote': 'مرن / عن بُعد', 'impact.slots': '{{count}} أماكن', 'impact.notFound': 'هذه الفرصة لم تعد متاحة', 'impact.participationUnavailable': 'تفاصيل الفرصة غير متاحة', 'impact.organizationUnavailable': 'مشاركتك ما زالت مسجلة.', 'impact.errorTitle': 'تعذر تحميل الأثر', 'impact.errorCopy': 'لم يتم تحميل بيانات الأثر. حاول مرة أخرى.', 'impact.actionError': 'تعذر إتمام الإجراء', 'impact.actionErrorCopy': 'حاول مرة أخرى.', 'impact.historyOnly': 'يبقى سجلك ومساهماتك ظاهرين أثناء انتظار التحقق. لا تتاح المشاركة في فرص جديدة.', 'impact.verification': 'تحقق الطالب', 'impact.dispute': 'اعترض على النتيجة', 'impact.disputeTitle': 'اطلب مراجعة النتيجة', 'impact.disputePlaceholder': 'اذكر سبب مراجعة هذه النتيجة', 'impact.submitDispute': 'إرسال الاعتراض', 'impact.requestReview': 'اطلب مراجعة المشرف', 'impact.reviewRequested': 'تم طلب مراجعة المشرف.', 'impact.reviewRequestedTitle': 'تم إرسال الطلب', 'impact.reviewRequestedCopy': 'يمكن للمشرف الآن رؤية طلب المراجعة.', 'impact.join': 'انضم', 'impact.cancel': 'إلغاء المشاركة', 'impact.starts': 'يبدأ: {{date}}', 'impact.dueDate': 'الموعد: {{date}}', 'impact.status.joined': 'منضم', 'impact.status.overdue': 'بانتظار المراجعة', 'impact.status.completed': 'مكتمل', 'impact.status.cancelled': 'ملغى', 'impact.status.cancelled_by_organization': 'ألغتها المنظمة', 'impact.status.no_show': 'لم يحضر', 'impact.status.excused': 'معذور', 'impact.status.expired_incomplete': 'انتهت دون إكمال', 'impact.status.disputed': 'قيد النزاع' },
} as const;

const nativeGiverAuthTranslations = {
  ro: { 'auth.giverSignup.entry': 'Creează cont Giver', 'auth.giverSignup.title': 'Creează cont Giver', 'auth.giverSignup.subtitle': 'Primește un email pentru confirmarea contului.', 'auth.giverSignup.submit': 'Creează contul', 'auth.giverSignup.submitting': 'Se creează…', 'auth.giverSignup.confirmTitle': 'Verifică emailul', 'auth.giverSignup.confirmCopy': 'Dacă datele sunt valide, vei primi un email pentru confirmarea contului.', 'auth.giverSignup.confirming': 'Confirmăm contul…', 'auth.giverSignup.errorTitle': 'Nu am putut crea contul' },
  en: { 'auth.giverSignup.entry': 'Create a Giver account', 'auth.giverSignup.title': 'Create a Giver account', 'auth.giverSignup.subtitle': 'We will email you a confirmation link.', 'auth.giverSignup.submit': 'Create account', 'auth.giverSignup.submitting': 'Creating account…', 'auth.giverSignup.confirmTitle': 'Check your email', 'auth.giverSignup.confirmCopy': 'If the details are valid, you will receive an email to confirm your account.', 'auth.giverSignup.confirming': 'Confirming your account…', 'auth.giverSignup.errorTitle': 'Could not create the account' },
  tr: { 'auth.giverSignup.entry': 'Giver hesabı oluştur', 'auth.giverSignup.title': 'Giver hesabı oluştur', 'auth.giverSignup.subtitle': 'Hesap onay bağlantısını e-postayla göndereceğiz.', 'auth.giverSignup.submit': 'Hesap oluştur', 'auth.giverSignup.submitting': 'Oluşturuluyor…', 'auth.giverSignup.confirmTitle': 'E-postanı kontrol et', 'auth.giverSignup.confirmCopy': 'Bilgiler geçerliyse hesabını onaylamak için e-posta alacaksın.', 'auth.giverSignup.confirming': 'Hesabın onaylanıyor…', 'auth.giverSignup.errorTitle': 'Hesap oluşturulamadı' },
  ar: { 'auth.giverSignup.entry': 'أنشئ حساب مانح', 'auth.giverSignup.title': 'أنشئ حساب مانح', 'auth.giverSignup.subtitle': 'سنرسل إليك رابط تأكيد عبر البريد الإلكتروني.', 'auth.giverSignup.submit': 'إنشاء الحساب', 'auth.giverSignup.submitting': 'جارٍ إنشاء الحساب…', 'auth.giverSignup.confirmTitle': 'تحقق من بريدك الإلكتروني', 'auth.giverSignup.confirmCopy': 'إذا كانت البيانات صالحة، ستتلقى رسالة لتأكيد حسابك.', 'auth.giverSignup.confirming': 'جارٍ تأكيد الحساب…', 'auth.giverSignup.errorTitle': 'تعذر إنشاء الحساب' },
} as const;

export const translations = {
  ro: { ...baseTranslations.ro, ...nativeGiverAuthTranslations.ro, ...verificationResubmissionTranslations.ro, ...mobileBoundaryTranslations.ro, ...workspaceTranslations.ro, ...nativeGiverReadTranslations.ro, ...nativeGiverShellTranslations.ro, ...impactTranslations.ro },
  en: { ...baseTranslations.en, ...nativeGiverAuthTranslations.en, ...verificationResubmissionTranslations.en, ...mobileBoundaryTranslations.en, ...workspaceTranslations.en, ...nativeGiverReadTranslations.en, ...nativeGiverShellTranslations.en, ...impactTranslations.en },
  tr: { ...baseTranslations.tr, ...nativeGiverAuthTranslations.tr, ...verificationResubmissionTranslations.tr, ...mobileBoundaryTranslations.tr, ...workspaceTranslations.tr, ...nativeGiverReadTranslations.tr, ...nativeGiverShellTranslations.tr, ...impactTranslations.tr },
  ar: { ...baseTranslations.ar, ...nativeGiverAuthTranslations.ar, ...verificationResubmissionTranslations.ar, ...mobileBoundaryTranslations.ar, ...workspaceTranslations.ar, ...nativeGiverReadTranslations.ar, ...nativeGiverShellTranslations.ar, ...impactTranslations.ar },
} as const;

export type SupportedLocale = keyof typeof translations;
export type TranslationKey = keyof typeof translations.ro;
