import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { AdminNav } from '@/components/admin-nav';
import { getWebLocale } from '@/lib/i18n/server';
import { formatWebDate, formatWebMoney } from '@/lib/i18n/web';

export default async function Operations() {
  const [db, locale] = await Promise.all([createClient(), getWebLocale()]); const { data: { user } } = await db.auth.getUser(); if (!user) redirect('/login');
  const { data: me } = await db.from('profiles').select('role').eq('id', user.id).single(); if (me?.role !== 'admin') redirect('/');
  const [{ data: claims, error: claimsError }, { data: orders, error: ordersError }, { data: payments, error: paymentsError }, { data: redemptions, error: redemptionsError }, { data: partnerAccess, error: partnerAccessError }] = await Promise.all([
    db.from('claims').select('status,claimed_at,expires_at,redeemed_at,campaigns(name,offers(name,partners(name)))').order('claimed_at', { ascending: false }).limit(50), db.from('giver_orders').select('status,total_bani,created_at,paid_at,profiles!giver_orders_giver_id_fkey(email),giver_order_items(quantity,offers(name)),payments(status)').order('created_at', { ascending: false }).limit(50), db.from('payments').select('status,provider,amount_bani,created_at,confirmed_at,giver_orders(profiles!giver_orders_giver_id_fkey(email))').order('created_at', { ascending: false }).limit(50), db.from('redemption_events').select('redeemed_at,partners(name),claims(status,campaigns(name,offers(name))),profiles!redemption_events_partner_user_id_fkey(email)').order('redeemed_at', { ascending: false }).limit(50), db.from('partner_user_access_events').select('action,created_at,partners(name),profiles!partner_user_access_events_user_id_fkey(email),actor:profiles!partner_user_access_events_actor_id_fkey(email)').order('created_at', { ascending: false }).limit(50),
  ]);
  const when = (value: string | null) => formatWebDate(locale, value); const money = (bani: number) => formatWebMoney(locale, bani);
  return <main className="shell operational-shell admin-v1-page py-10"><div className="page-heading"><div><p className="eyebrow">Core operations</p><h1>Operational records</h1><p>Read-only visibility for claims, redemptions, funding records, and partner access. QR credentials and claim secrets are never shown.</p></div></div><AdminNav current="/admin/operations" />
    <Section title="Claims" error={claimsError} empty="No recent claims are available."><table><thead><tr><th>Offer / campaign</th><th>State</th><th>Claimed</th><th>Expires</th><th>Redeemed</th></tr></thead><tbody>{claims?.map((claim: any, index) => <tr key={`${claim.claimed_at}-${index}`}><td>{claim.campaigns?.offers?.name || 'Offer unavailable'}<small>{claim.campaigns?.name || 'Campaign unavailable'} · {claim.campaigns?.offers?.partners?.name || 'Partner unavailable'}</small></td><td><Status value={claim.status}/></td><td>{when(claim.claimed_at)}</td><td>{when(claim.expires_at)}</td><td>{when(claim.redeemed_at)}</td></tr>)}</tbody></table></Section>
    <Section title="Giver orders" error={ordersError} empty="No recent giver orders are available."><table><thead><tr><th>Giver</th><th>Items</th><th>Total</th><th>Order / payment</th><th>Created</th><th>Paid</th></tr></thead><tbody>{orders?.map((order: any, index) => <tr key={`${order.created_at}-${index}`}><td>{order.profiles?.email || 'Giver account unavailable'}</td><td>{order.giver_order_items?.map((item: any) => `${item.quantity}× ${item.offers?.name || 'Offer'}`).join(', ') || 'No item detail'}</td><td>{money(order.total_bani)}</td><td><Status value={order.status}/> / <Status value={order.payments?.status || 'unknown'}/></td><td>{when(order.created_at)}</td><td>{when(order.paid_at)}</td></tr>)}</tbody></table></Section>
    <Section id="payments" title="Payments" error={paymentsError} empty="No recent payment records are available."><table><thead><tr><th>Giver</th><th>Provider</th><th>Amount</th><th>State</th><th>Created</th><th>Confirmed</th></tr></thead><tbody>{payments?.map((payment: any, index) => <tr key={`${payment.created_at}-${index}`}><td>{payment.giver_orders?.profiles?.email || 'Giver account unavailable'}</td><td>{payment.provider}</td><td>{money(payment.amount_bani)}</td><td><Status value={payment.status}/></td><td>{when(payment.created_at)}</td><td>{when(payment.confirmed_at)}</td></tr>)}</tbody></table></Section>
    <Section title="Redemptions" error={redemptionsError} empty="No recent redemptions are available."><table><thead><tr><th>Partner</th><th>Offer / campaign</th><th>Claim state</th><th>Partner user</th><th>Redeemed</th></tr></thead><tbody>{redemptions?.map((event: any, index) => <tr key={`${event.redeemed_at}-${index}`}><td>{event.partners?.name || 'Partner unavailable'}</td><td>{event.claims?.campaigns?.offers?.name || 'Offer unavailable'}<small>{event.claims?.campaigns?.name || 'Campaign unavailable'}</small></td><td><Status value={event.claims?.status || 'unknown'}/></td><td>{event.profiles?.email || 'Partner account unavailable'}</td><td>{when(event.redeemed_at)}</td></tr>)}</tbody></table></Section>
    <Section title="Partner access history" error={partnerAccessError} empty="No recent partner access changes are available."><table><thead><tr><th>Partner</th><th>Account</th><th>Action</th><th>Recorded by</th><th>When</th></tr></thead><tbody>{partnerAccess?.map((event: any, index) => <tr key={`${event.created_at}-${index}`}><td>{event.partners?.name || 'Partner unavailable'}</td><td>{event.profiles?.email || 'Account unavailable'}</td><td>{event.action}</td><td>{event.actor?.email || 'System'}</td><td>{when(event.created_at)}</td></tr>)}</tbody></table></Section>
  </main>;
}
function Section({ id, title, error, empty, children }: { id?: string; title: string; error: unknown; empty: string; children: React.ReactNode }) { return <section id={id} className="card admin-table-section"><div className="section-heading"><h2>{title}</h2><p>{error ? 'This operational record type could not be loaded.' : empty}</p></div>{error ? <div className="empty-state error-state">Refresh the page and try again.</div> : <div className="admin-table-wrap">{children}</div>}</section>; }
function Status({ value }: { value: string }) { return <span className={`status status-${value}`}>{value.replaceAll('_', ' ')}</span>; }
