import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { redirect } from 'next/navigation';
import { AdminNav } from '@/components/admin-nav';
import { assignPartnerUser, createCampaign, createCategory, createOffer, createPartner, createUniversity, revokePartnerUser, setOperationalState, updateCampaign, updateOffer, updatePartner } from '../actions';

type Choice = { id: string; name: string };
const datetimeValue = (date: Date) => date.toISOString().slice(0, 16);

export default async function Manage() {
  const db = await createClient(); const { data: { user } } = await db.auth.getUser(); if (!user) redirect('/login');
  const { data: me } = await db.from('profiles').select('role').eq('id', user.id).single(); if (me?.role !== 'admin') redirect('/');
  const [{ data: universities }, { data: categories }, { data: partners }, { data: offers }, { data: campaigns }, { data: users }, { data: memberships }] = await Promise.all([
    db.from('universities').select('id,name,active').order('sort_order'),
    db.from('categories').select('id,name,slug,active').order('sort_order'),
    db.from('partners').select('id,name,slug,description,address,city,phone,website,booking_url,active').order('name'),
    db.from('offers').select('id,partner_id,category_id,name,description,image_path,localization_key,giver_price_bani,internal_redemption_value_bani,fulfillment_type,redemption_instructions,booking_url,active,partners(name),categories(name)').order('name'),
    db.from('campaigns').select('id,offer_id,name,status,quantity_total,quantity_available,starts_at,ends_at,claim_expiration_minutes,event_starts_at,event_ends_at,sponsor_type,sponsor_display_name,giver_order_id,offers(name,fulfillment_type,partners(name))').order('created_at', { ascending: false }).limit(40),
    db.from('profiles').select('id,email,role').eq('role', 'partner').order('email'),
    db.from('partner_users').select('partner_id,user_id,profiles(email,role)').order('created_at'),
  ]);
  const partnerChoices = (partners ?? []).map((partner) => ({ id: partner.id, name: partner.name }));
  const categoryChoices = (categories ?? []).map((category) => ({ id: category.id, name: category.name }));
  const offerChoices = (offers ?? []).map((offer: any) => ({ id: offer.id, name: `${offer.name} · ${offer.partners?.name ?? ''}` }));
  const userChoices = (users ?? []).map((profile) => ({ id: profile.id, name: profile.email }));
  const defaults = { start: datetimeValue(new Date()), end: datetimeValue(new Date(Date.now() + 30 * 86400000)) };

  return <main className="shell operational-shell admin-v1-page py-10"><span id="campaigns" className="sr-only">Campaign management</span><AdminNav current="/admin/manage" />
    <div className="flex flex-wrap gap-4"><Link href="/admin" className="font-bold text-forest">← Admin</Link><Link href="/admin/operations" className="font-bold text-forest">Vezi operațiunile</Link></div>
    <h1 className="mt-4 text-4xl font-black">Gestionare operațională</h1>
    <p className="mt-2 text-stone-600">Editează catalogul și planificarea. Tranzacțiile, cantitățile finanțate și istoricul rămân imuabile.</p>

    <section className="mt-8 grid gap-5 lg:grid-cols-2">
      <Form title="Universitate" action={createUniversity}><Field n="name" l="Nume" /></Form>
      <Form title="Categorie" action={createCategory}><Field n="name" l="Nume" /><Field n="slug" l="Slug" /><Field n="icon" l="Identificator icon" d="sparkles" /></Form>
      <PartnerFields title="Partener nou" action={createPartner} />
      <OfferFields title="Ofertă nouă" action={createOffer} partners={partnerChoices} categories={categoryChoices} />
      <CampaignFields title="Campanie nouă" action={createCampaign} offers={offerChoices} defaults={defaults} />
      <Form title="Atribuie utilizator partenerului" action={assignPartnerUser}><Select n="partnerId" l="Partener" items={partnerChoices} /><Select n="userId" l="Utilizator partener" items={userChoices} /><p className="mt-3 text-sm text-stone-600">Sunt eligibili doar utilizatorii cu rolul Partner.</p></Form>
    </section>

    <section className="mt-12"><h2 className="text-2xl font-black">Parteneri</h2><div className="mt-4 grid gap-4">{partners?.map((partner) => <details className="card" key={partner.id}><summary className="cursor-pointer font-black">{partner.name} · {partner.active ? 'activ' : 'inactiv'}</summary><div className="mt-4 grid gap-5 lg:grid-cols-2"><PartnerFields title="Detalii" action={updatePartner} partner={partner} /><div><h3 className="font-black">Utilizatori atribuiți</h3>{memberships?.filter((membership) => membership.partner_id === partner.id).map((membership: any) => <div className="mt-2 flex items-center justify-between gap-3 text-sm" key={membership.user_id}><span>{membership.profiles?.email ?? membership.user_id}</span><form action={revokePartnerUser}><input type="hidden" name="partnerId" value={partner.id} /><input type="hidden" name="userId" value={membership.user_id} /><button className="text-coral underline">Revocă accesul</button></form></div>)}<StateForm kind="partners" id={partner.id} active={partner.active} /></div></div></details>)}</div></section>

    <section className="mt-12"><h2 className="text-2xl font-black">Oferte</h2><div className="mt-4 grid gap-4">{offers?.map((offer: any) => <details className="card" key={offer.id}><summary className="cursor-pointer font-black">{offer.name} · {offer.partners?.name} · {offer.active ? 'activă' : 'inactivă'}</summary><div className="mt-4"><OfferFields title="Detalii ofertă" action={updateOffer} partners={partnerChoices} categories={categoryChoices} offer={offer} /><StateForm kind="offers" id={offer.id} active={offer.active} /></div></details>)}</div></section>

    <section className="mt-12"><h2 className="text-2xl font-black">Campanii</h2><p className="mt-2 text-sm text-stone-600">Cantitatea totală și disponibilă nu pot fi editate. Planificarea poate fi schimbată doar înainte de primul claim. Campaniile încheiate sunt read-only.</p><div className="mt-4 grid gap-4">{campaigns?.map((campaign: any) => <details className="card" key={campaign.id}><summary className="cursor-pointer font-black">{campaign.name} · {campaign.offers?.name} · {campaign.quantity_available}/{campaign.quantity_total} · {campaign.status}</summary><p className="mt-3 text-sm text-stone-600">{campaign.giver_order_id ? 'Finanțată prin comandă giver' : 'Campanie administrată'} · {campaign.offers?.fulfillment_type}</p>{campaign.status === 'ended' ? <p className="mt-4 text-sm text-stone-600">Campania încheiată rămâne disponibilă doar pentru istoric.</p> : <CampaignFields title="Planificare și statut" action={updateCampaign} offers={offerChoices} defaults={defaults} campaign={campaign} />}</details>)}</div></section>

    <section className="mt-12"><h2 className="text-2xl font-black">Stare universități și categorii</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{[['universities', universities], ['categories', categories]].map(([kind, entries]: any) => <div className="card" key={kind}><h3 className="font-black">{kind === 'universities' ? 'Universități' : 'Categorii'}</h3>{entries?.map((entry: any) => <div className="mt-3 flex items-center justify-between gap-3 text-sm" key={entry.id}><span>{entry.name}</span><StateForm kind={kind} id={entry.id} active={entry.active} compact /></div>)}</div>)}</div></section>
  </main>;
}

function Form({ title, action, children }: { title: string; action: (form: FormData) => void; children: React.ReactNode }) { return <form className="card" action={action}><h2 className="text-xl font-black">{title}</h2>{children}<button className="btn mt-5">Salvează</button></form>; }
function Field({ n, l, type = 'text', d, required = false }: { n: string; l: string; type?: string; d?: string | number | null; required?: boolean }) { return <label>{l}<input name={n} type={type} defaultValue={d ?? ''} required={required} /></label>; }
function Select({ n, l, items, selected }: { n: string; l: string; items: Choice[]; selected?: string }) { return <label>{l}<select name={n} defaultValue={selected ?? ''} required><option value="">Alege</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }
function StateForm({ kind, id, active, compact = false }: { kind: 'categories' | 'partners' | 'offers' | 'universities'; id: string; active: boolean; compact?: boolean }) { return <form action={setOperationalState} className={compact ? '' : 'mt-5'}><input type="hidden" name="kind" value={kind} /><input type="hidden" name="id" value={id} /><input type="hidden" name="active" value={String(!active)} /><button className={active ? 'text-coral underline' : 'text-forest underline'}>{active ? 'Dezactivează' : 'Activează'}</button></form>; }
function PartnerFields({ title, action, partner }: { title: string; action: (form: FormData) => void; partner?: any }) { return <Form title={title} action={action}>{partner && <input type="hidden" name="id" value={partner.id} />}<Field n="name" l="Nume" d={partner?.name} required /><Field n="slug" l="Slug" d={partner?.slug} required /><Field n="address" l="Adresă" d={partner?.address} required /><Field n="city" l="Oraș" d={partner?.city ?? 'București'} required /><Field n="description" l="Descriere" d={partner?.description} /><Field n="phone" l="Telefon" d={partner?.phone} /><Field n="website" l="Website" d={partner?.website} /><Field n="bookingUrl" l="URL programare" d={partner?.booking_url} /></Form>; }
function OfferFields({ title, action, partners, categories, offer }: { title: string; action: (form: FormData) => void; partners: Choice[]; categories: Choice[]; offer?: any }) { return <Form title={title} action={action}>{offer && <input type="hidden" name="id" value={offer.id} />}<Select n="partnerId" l="Partener" items={partners} selected={offer?.partner_id} /><Select n="categoryId" l="Categorie" items={categories} selected={offer?.category_id} /><Field n="name" l="Nume" d={offer?.name} required /><Field n="description" l="Descriere" d={offer?.description} required /><Field n="price" l="Preț giver (bani)" type="number" d={offer?.giver_price_bani ?? 1500} required /><Field n="internalValue" l="Valoare internă (bani, opțional)" type="number" d={offer?.internal_redemption_value_bani} /><label>Fulfillment<select name="fulfillment" defaultValue={offer?.fulfillment_type ?? 'instant'}><option value="instant">instant</option><option value="appointment_required">appointment_required</option><option value="scheduled_event">scheduled_event</option></select></label><Field n="instructions" l="Instrucțiuni" d={offer?.redemption_instructions} /><Field n="bookingUrl" l="URL programare" d={offer?.booking_url} /><Field n="imagePath" l="Image path" d={offer?.image_path} /><Field n="localizationKey" l="Cheie localizare" d={offer?.localization_key} /></Form>; }
function CampaignFields({ title, action, offers, defaults, campaign }: { title: string; action: (form: FormData) => void; offers: Choice[]; defaults: { start: string; end: string }; campaign?: any }) { return <Form title={title} action={action}>{campaign ? <><input type="hidden" name="id" value={campaign.id} /><input type="hidden" name="offerId" value={campaign.offer_id} /><input type="hidden" name="quantity" value={campaign.quantity_total} /><input type="hidden" name="sponsor" value={campaign.sponsor_type} /><input type="hidden" name="display" value={campaign.sponsor_display_name ?? ''} /><p className="mt-3 text-sm text-stone-600">Oferta, sponsorul și inventarul nu se schimbă după creare.</p></> : <Select n="offerId" l="Ofertă" items={offers} />}<Field n="name" l="Nume campanie" d={campaign?.name} required />{!campaign && <Field n="quantity" l="Cantitate finanțată" type="number" d={10} required />}<Field n="startsAt" l="Începe la" type="datetime-local" d={campaign ? datetimeValue(new Date(campaign.starts_at)) : defaults.start} required /><Field n="endsAt" l="Se termină la" type="datetime-local" d={campaign ? datetimeValue(new Date(campaign.ends_at)) : defaults.end} required /><Field n="eventStartsAt" l="Începe evenimentul (doar scheduled_event)" type="datetime-local" d={campaign?.event_starts_at ? datetimeValue(new Date(campaign.event_starts_at)) : ''} /><Field n="eventEndsAt" l="Se termină evenimentul (doar scheduled_event)" type="datetime-local" d={campaign?.event_ends_at ? datetimeValue(new Date(campaign.event_ends_at)) : ''} /><Field n="expiry" l="Expirare claim (minute, opțional)" type="number" d={campaign?.claim_expiration_minutes ?? 60} />{!campaign && <><label>Sponsor<select name="sponsor" defaultValue="cinste"><option value="cinste">CINSTE</option><option value="individual">individual</option><option value="company">company</option><option value="creator">creator</option><option value="partner">partner</option></select></label><Field n="display" l="Nume sponsor public" /></>}<label>Statut<select name="status" defaultValue={campaign?.status ?? 'active'}><option value="draft">draft</option><option value="active">active</option><option value="paused">paused</option></select></label></Form>; }
