import { Pressable, StyleSheet, Text, View } from 'react-native';

import { color, radius, space, type } from '@/design/tokens';
import { OfferVisual } from './offer-visual';

export function OfferCard({ category, categorySlug, title, partner, availability, fulfillment, imageUrl, onPress, rtl = false }: { category: string; categorySlug: string; title: string; partner: string; availability: string; fulfillment: string; imageUrl?: string | null; onPress: () => void; rtl?: boolean }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={`${title}, ${partner}`} onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><OfferVisual categorySlug={categorySlug} imageUrl={imageUrl} compact /><View style={[styles.body, rtl && styles.rtl]}><View style={[styles.metaRow, rtl && styles.rowRtl]}><Text style={[styles.category, rtl && styles.textRtl]} numberOfLines={1}>{category}</Text><View style={styles.treatDot} /></View><Text style={[styles.title, rtl && styles.textRtl]} numberOfLines={2}>{title}</Text><Text style={[styles.partner, rtl && styles.textRtl]} numberOfLines={1}>{partner}</Text><View style={[styles.footer, rtl && styles.rowRtl]}><Text style={[styles.availability, rtl && styles.textRtl]} numberOfLines={1}>{availability}</Text><Text style={[styles.fulfillment, rtl && styles.textRtl]} numberOfLines={1}>{fulfillment}</Text></View></View></Pressable>;
}

const styles = StyleSheet.create({ card: { backgroundColor: color.surface, borderRadius: radius.card, overflow: 'hidden', borderWidth: 1, borderColor: color.line }, pressed: { opacity: .82 }, body: { padding: space.md, gap: 5 }, rtl: { direction: 'rtl' }, rowRtl: { flexDirection: 'row-reverse' }, textRtl: { writingDirection: 'rtl', textAlign: 'right' }, metaRow: { flexDirection: 'row', alignItems: 'center', gap: 7 }, category: { ...type.meta, color: color.brand, flexShrink: 1 }, treatDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: color.coral }, title: { ...type.cardTitle, color: color.ink, marginTop: 3 }, partner: { ...type.meta, color: color.muted }, footer: { marginTop: space.sm, paddingTop: space.sm, borderTopWidth: 1, borderTopColor: color.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: space.sm }, availability: { ...type.meta, color: color.muted, flex: 1 }, fulfillment: { ...type.meta, color: color.brand, flexShrink: 1 } });
