import { ActivityIndicator, Pressable, StyleSheet, Text, View, type StyleProp, type ViewStyle } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { color, radius, shadow, space, type } from '@/design/tokens';

export const colors = { ink: color.ink, cream: color.canvas, coral: color.coral, mint: color.mint, forest: color.brand, muted: color.muted, border: color.line, white: color.surface };

export function ScreenContainer({ children, style }: { children: React.ReactNode; style?: StyleProp<ViewStyle> }) { return <SafeAreaView edges={['left', 'right']} style={[styles.screen, style]}>{children}</SafeAreaView>; }
export function Button({ label, onPress, variant = 'primary', disabled = false }: { label: string; onPress: () => void; variant?: 'primary' | 'coral' | 'quiet'; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={[styles.button, variant === 'coral' && styles.coral, variant === 'quiet' && styles.quiet, disabled && styles.disabled]}><Text style={[styles.buttonText, variant === 'quiet' && styles.quietText]}>{label}</Text></Pressable>; }
export function Pill({ children, color: tone = 'mint', rtl = false }: { children: React.ReactNode; color?: 'mint' | 'coral'; rtl?: boolean }) { return <View style={[styles.pill, tone === 'coral' && styles.coralPill, rtl && styles.pillRtl]}><Text style={[styles.pillText, tone === 'coral' && styles.coralPillText, rtl && styles.rtlText]}>{children}</Text></View>; }
export function Card({ children, style }: { children: React.ReactNode; style?: StyleProp<ViewStyle> }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Loading({ label = '…' }: { label?: string }) { return <View accessibilityRole="progressbar" style={styles.loading}><ActivityIndicator color={color.brand}/><Text style={styles.muted}>{label}</Text></View>; }
export function EmptyState({ title, copy }: { title: string; copy: string }) { return <View style={styles.empty}><View style={styles.emptyMark} /><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyCopy}>{copy}</Text></View>; }

export const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: color.canvas }, button: { minHeight: 54, paddingHorizontal: space.lg, borderRadius: radius.button, backgroundColor: color.brand, justifyContent: 'center', alignItems: 'center' }, coral: { backgroundColor: color.coral }, quiet: { backgroundColor: color.surface, borderWidth: 1, borderColor: color.line }, disabled: { opacity: .5 }, buttonText: { ...type.label, color: color.surface }, quietText: { color: color.ink }, pill: { alignSelf: 'flex-start', backgroundColor: color.mint, borderRadius: radius.pill, paddingHorizontal: 10, paddingVertical: 5 }, pillRtl: { alignSelf: 'flex-end' }, coralPill: { backgroundColor: color.peach }, pillText: { ...type.meta, color: color.brand }, rtlText: { writingDirection: 'rtl', textAlign: 'right' }, coralPillText: { color: color.danger }, card: { backgroundColor: color.surface, borderRadius: radius.card, padding: space.lg, borderWidth: 1, borderColor: color.line }, loading: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: space.sm, backgroundColor: color.canvas }, muted: { ...type.body, color: color.muted }, empty: { alignItems: 'center', paddingHorizontal: space.xxl, paddingVertical: 44, backgroundColor: color.surface, borderRadius: radius.card, borderWidth: 1, borderColor: color.line }, emptyMark: { width: 30, height: 7, borderRadius: radius.pill, backgroundColor: color.coral, marginBottom: space.md }, emptyTitle: { ...type.section, color: color.ink, textAlign: 'center' }, emptyCopy: { ...type.body, color: color.muted, textAlign: 'center', marginTop: space.xs } });
