import type { WebLocale } from './web';

type Copy = { drafts: string; hint: string; newDraft: string; partner: string; category: string; name: string; description: string; fulfillment: string; instructions: string; booking: string; submit: string; empty: string };
export const partnerOfferCopies: Record<WebLocale, Copy> = {
  ro: { drafts: 'Propuneri de oferte', hint: 'Trimite o propunere. CINSTE stabilește prețul și publică oferta numai după revizuire.', newDraft: 'Propune o ofertă', partner: 'Partener', category: 'Categorie', name: 'Numele ofertei', description: 'Descriere', fulfillment: 'Modalitate de folosire', instructions: 'Instrucțiuni de folosire', booking: 'Link de rezervare', submit: 'Trimite spre revizuire', empty: 'Nu ai trimis încă nicio propunere.' },
  en: { drafts: 'Offer proposals', hint: 'Submit a proposal. CINSTE sets the price and publishes an offer only after review.', newDraft: 'Propose an offer', partner: 'Partner', category: 'Category', name: 'Offer name', description: 'Description', fulfillment: 'Fulfillment', instructions: 'Redemption instructions', booking: 'Booking link', submit: 'Submit for review', empty: 'You have not submitted an offer proposal yet.' },
  tr: { drafts: 'Teklif önerileri', hint: 'Bir öneri gönderin. CINSTE fiyatı belirler ve teklifi yalnızca incelemeden sonra yayımlar.', newDraft: 'Teklif öner', partner: 'İş ortağı', category: 'Kategori', name: 'Teklif adı', description: 'Açıklama', fulfillment: 'Kullanım şekli', instructions: 'Kullanım talimatları', booking: 'Rezervasyon bağlantısı', submit: 'İncelemeye gönder', empty: 'Henüz bir teklif önerisi göndermediniz.' },
  ar: { drafts: 'مقترحات العروض', hint: 'أرسل مقترحاً. تحدد CINSTE السعر ولا تنشر العرض إلا بعد المراجعة.', newDraft: 'اقترح عرضاً', partner: 'الشريك', category: 'الفئة', name: 'اسم العرض', description: 'الوصف', fulfillment: 'طريقة الاستخدام', instructions: 'تعليمات الاستخدام', booking: 'رابط الحجز', submit: 'إرسال للمراجعة', empty: 'لم ترسل مقترح عرض بعد.' },
};
