import type { WebLocale } from './web';

type Values = Record<string, string | number>;
type Copy = Record<string, string>;

/** Locale-aware labels for stored domain states. Values remain backend enums. */
export const webPresentation: Record<WebLocale, Copy> = {
  ro: { available: 'Disponibil', unavailable: 'Indisponibil', active: 'Activ', inactive: 'Inactiv', pending: 'În așteptare', pending_review: 'În așteptarea revizuirii', verified: 'Verificat', rejected: 'Respins', failed: 'Eșuat', paid: 'Plătit', draft: 'Ciornă', published: 'Publicat', cancelled: 'Anulat', completed: 'Finalizat', joined: 'Înscris', overdue: 'În revizuire pentru întârziere', disputed: 'În revizuire de Admin', no_show: 'Absent', excused: 'Scutit', cancelled_by_organization: 'Anulat de organizație', late_cancelled: 'Anulare târzie', expired_incomplete: 'Expirat incomplet', privacy_suppressed: 'Detalii protejate', outcome_privacy: 'Detaliile rezultatului sunt ascunse pentru grupurile mici, pentru a proteja confidențialitatea studenților.', outcome_unavailable: 'Rezultatele detaliate nu sunt disponibile pentru această contribuție.', redemption_VALID_title: 'Gata de răscumpărare', redemption_VALID_body: 'Confirmă numai după ce experiența a fost oferită studentului.', redemption_REDEEMED_title: 'Răscumpărat cu succes', redemption_REDEEMED_body: 'CINSTE-ul a fost confirmat. Poți continua cu următoarea scanare.', redemption_INVALID_CODE_title: 'Cod invalid', redemption_INVALID_CODE_body: 'Verifică codul sau scanează din nou.', redemption_ALREADY_REDEEMED_title: 'Deja răscumpărat', redemption_ALREADY_REDEEMED_body: 'Acest CINSTE a fost deja folosit.', redemption_EXPIRED_title: 'Expirat', redemption_EXPIRED_body: 'Acest CINSTE nu mai este valabil.', redemption_NOT_VALID_AT_THIS_PARTNER_title: 'Alt partener', redemption_NOT_VALID_AT_THIS_PARTNER_body: 'Acest CINSTE aparține altui partener.', redemption_NOT_YET_VALID_title: 'Încă nu este valabil', redemption_NOT_YET_VALID_body: 'Acest CINSTE nu poate fi răscumpărat încă.', redemption_ERROR_title: 'Nu am putut finaliza', redemption_ERROR_body: 'Încearcă din nou. Dacă problema continuă, folosește codul manual sau contactează CINSTE.', redemption_unknown_title: 'CINSTE indisponibil', redemption_unknown_body: 'Detaliile acestei experiențe nu sunt disponibile acum. Nu confirma răscumpărarea.' },
  en: { available: 'Available', unavailable: 'Unavailable', active: 'Active', inactive: 'Inactive', pending: 'Pending', pending_review: 'Pending review', verified: 'Verified', rejected: 'Rejected', failed: 'Failed', paid: 'Paid', draft: 'Draft', published: 'Published', cancelled: 'Cancelled', completed: 'Completed', joined: 'Joined', overdue: 'Overdue review', disputed: 'Admin review', no_show: 'No show', excused: 'Excused', cancelled_by_organization: 'Cancelled by organization', late_cancelled: 'Late cancellation', expired_incomplete: 'Expired incomplete', privacy_suppressed: 'Details protected', outcome_privacy: 'Outcome details are hidden for small groups to protect student privacy.', outcome_unavailable: 'Detailed outcomes are unavailable for this contribution.', redemption_VALID_title: 'Ready to redeem', redemption_VALID_body: 'Confirm only after the student has received the experience.', redemption_REDEEMED_title: 'Redeemed successfully', redemption_REDEEMED_body: 'The CINSTE has been confirmed. You can continue with the next scan.', redemption_INVALID_CODE_title: 'Invalid code', redemption_INVALID_CODE_body: 'Check the code or scan again.', redemption_ALREADY_REDEEMED_title: 'Already redeemed', redemption_ALREADY_REDEEMED_body: 'This CINSTE has already been used.', redemption_EXPIRED_title: 'Expired', redemption_EXPIRED_body: 'This CINSTE is no longer valid.', redemption_NOT_VALID_AT_THIS_PARTNER_title: 'Different partner', redemption_NOT_VALID_AT_THIS_PARTNER_body: 'This CINSTE belongs to another partner.', redemption_NOT_YET_VALID_title: 'Not valid yet', redemption_NOT_YET_VALID_body: 'This CINSTE cannot be redeemed yet.', redemption_ERROR_title: 'Could not complete', redemption_ERROR_body: 'Try again. If the issue continues, use the manual code or contact CINSTE.', redemption_unknown_title: 'CINSTE unavailable', redemption_unknown_body: 'Details for this experience are unavailable now. Do not confirm redemption.' },
  tr: { available: 'Mevcut', unavailable: 'Kullanılamıyor', active: 'Aktif', inactive: 'Pasif', pending: 'Beklemede', pending_review: 'İnceleme bekliyor', verified: 'Doğrulandı', rejected: 'Reddedildi', failed: 'Başarısız', paid: 'Ödendi', draft: 'Taslak', published: 'Yayınlandı', cancelled: 'İptal edildi', completed: 'Tamamlandı', joined: 'Katıldı', overdue: 'Gecikme incelemesi', disputed: 'Yönetici incelemesi', no_show: 'Gelmedi', excused: 'Mazeretli', cancelled_by_organization: 'Kuruluş tarafından iptal edildi', late_cancelled: 'Geç iptal', expired_incomplete: 'Eksik olarak sona erdi', privacy_suppressed: 'Ayrıntılar korundu', outcome_privacy: 'Öğrenci gizliliğini korumak için küçük gruplarda sonuç ayrıntıları gizlenir.', outcome_unavailable: 'Bu katkı için ayrıntılı sonuçlar kullanılamıyor.', redemption_VALID_title: 'Kullanıma hazır', redemption_VALID_body: 'Yalnızca öğrenci deneyimi aldıktan sonra onaylayın.', redemption_REDEEMED_title: 'Başarıyla kullanıldı', redemption_REDEEMED_body: 'CINSTE onaylandı. Sonraki taramaya devam edebilirsiniz.', redemption_INVALID_CODE_title: 'Geçersiz kod', redemption_INVALID_CODE_body: 'Kodu kontrol edin veya yeniden tarayın.', redemption_ALREADY_REDEEMED_title: 'Zaten kullanıldı', redemption_ALREADY_REDEEMED_body: 'Bu CINSTE zaten kullanıldı.', redemption_EXPIRED_title: 'Süresi doldu', redemption_EXPIRED_body: 'Bu CINSTE artık geçerli değil.', redemption_NOT_VALID_AT_THIS_PARTNER_title: 'Farklı iş ortağı', redemption_NOT_VALID_AT_THIS_PARTNER_body: 'Bu CINSTE başka bir iş ortağına aittir.', redemption_NOT_YET_VALID_title: 'Henüz geçerli değil', redemption_NOT_YET_VALID_body: 'Bu CINSTE henüz kullanılamaz.', redemption_ERROR_title: 'Tamamlanamadı', redemption_ERROR_body: 'Tekrar deneyin. Sorun sürerse manuel kodu kullanın veya CINSTE ile iletişime geçin.', redemption_unknown_title: 'CINSTE kullanılamıyor', redemption_unknown_body: 'Bu deneyimin ayrıntıları şu anda kullanılamıyor. Kullanımı onaylamayın.' },
  ar: { available: 'متاح', unavailable: 'غير متاح', active: 'نشط', inactive: 'غير نشط', pending: 'قيد الانتظار', pending_review: 'بانتظار المراجعة', verified: 'تم التحقق', rejected: 'مرفوض', failed: 'فشل', paid: 'مدفوع', draft: 'مسودة', published: 'منشور', cancelled: 'ملغى', completed: 'مكتمل', joined: 'منضم', overdue: 'مراجعة التأخير', disputed: 'مراجعة المشرف', no_show: 'لم يحضر', excused: 'معذور', cancelled_by_organization: 'ألغته المؤسسة', late_cancelled: 'إلغاء متأخر', expired_incomplete: 'انتهى غير مكتمل', privacy_suppressed: 'تفاصيل محمية', outcome_privacy: 'تُخفى تفاصيل النتائج للمجموعات الصغيرة لحماية خصوصية الطلاب.', outcome_unavailable: 'النتائج التفصيلية غير متاحة لهذه المساهمة.', redemption_VALID_title: 'جاهز للاسترداد', redemption_VALID_body: 'أكّد فقط بعد حصول الطالب على التجربة.', redemption_REDEEMED_title: 'تم الاسترداد بنجاح', redemption_REDEEMED_body: 'تم تأكيد CINSTE. يمكنك متابعة المسح التالي.', redemption_INVALID_CODE_title: 'رمز غير صالح', redemption_INVALID_CODE_body: 'تحقق من الرمز أو امسح مرة أخرى.', redemption_ALREADY_REDEEMED_title: 'تم استرداده بالفعل', redemption_ALREADY_REDEEMED_body: 'استُخدم CINSTE هذا بالفعل.', redemption_EXPIRED_title: 'منتهي الصلاحية', redemption_EXPIRED_body: 'لم يعد CINSTE هذا صالحاً.', redemption_NOT_VALID_AT_THIS_PARTNER_title: 'شريك مختلف', redemption_NOT_VALID_AT_THIS_PARTNER_body: 'هذا CINSTE تابع لشريك آخر.', redemption_NOT_YET_VALID_title: 'غير صالح بعد', redemption_NOT_YET_VALID_body: 'لا يمكن استرداد CINSTE هذا بعد.', redemption_ERROR_title: 'تعذر الإكمال', redemption_ERROR_body: 'حاول مرة أخرى. إذا استمرت المشكلة، استخدم الرمز اليدوي أو تواصل مع CINSTE.', redemption_unknown_title: 'CINSTE غير متاح', redemption_unknown_body: 'تفاصيل هذه التجربة غير متاحة الآن. لا تؤكد الاسترداد.' },
};

export function webLabel(locale: WebLocale, value: string, values: Values = {}) {
  let message = webPresentation[locale][value] ?? value.replaceAll('_', ' ');
  for (const [name, value] of Object.entries(values)) message = message.replace(`{{${name}}}`, String(value));
  return message;
}
