import { useCallback, useMemo, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { Card, EmptyState, Loading, Pill, colors } from '@/components/ui';
import { formatDate, useAppLocale } from '@/i18n';
import { impactParticipationDisplay, impactParticipationFromReadModel, type ImpactParticipation } from '@/lib/impact-participation';
import { getImpactOpportunities, getMyImpactParticipations, type ImpactOpportunity } from '@/lib/queries';
import { supabase } from '@/lib/supabase';

export default function Impact() {
  const { t, locale, isRTL } = useAppLocale(); const [opportunities, setOpportunities] = useState<ImpactOpportunity[]>([]); const [participations, setParticipations] = useState<ImpactParticipation[]>([]); const [metrics, setMetrics] = useState({ count: 0, minutes: 0, organizations: 0 }); const [due, setDue] = useState(false); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const [items, participationRows, contributionsResult, stateResult] = await Promise.all([getImpactOpportunities(), getMyImpactParticipations(), supabase.from('impact_contributions').select('verified_minutes,organization_id').is('revoked_at', null), supabase.from('impact_reciprocity_state').select('status').maybeSingle()]); const contributions = contributionsResult.data ?? []; setOpportunities(items); setParticipations(participationRows.map(impactParticipationFromReadModel)); setMetrics({ count: contributions.length, minutes: contributions.reduce((sum, item) => sum + item.verified_minutes, 0), organizations: new Set(contributions.map((item) => item.organization_id)).size }); setDue(stateResult.data?.status === 'give_back_due'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const active = useMemo(() => participations.filter((item) => ['joined', 'overdue'].includes(item.status)), [participations]);
  if (loading) return <Loading label={t('impact.loading')} />;
  return <FlatList data={opportunities} keyExtractor={(item) => item.id} contentContainerStyle={[styles.page, isRTL && styles.rtl]} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.forest} />} ListHeaderComponent={<View><Text style={[styles.title, isRTL && styles.textRtl]}>{t('impact.title')}</Text><Text style={[styles.copy, isRTL && styles.textRtl]}>{due ? t('impact.due') : t('impact.open')}</Text><Card style={[styles.metrics, isRTL && styles.metricsRtl]}><Metric value={String(metrics.count)} label={t('impact.contributions')} /><View style={styles.metricDivider}/><Metric value={`${Math.floor(metrics.minutes / 60)}h`} label={t('impact.minutes')} /><View style={styles.metricDivider}/><Metric value={String(metrics.organizations)} label={t('impact.organizations')} /></Card>{active.length > 0 && <><Text style={[styles.heading, isRTL && styles.textRtl]}>{t('impact.active')}</Text>{active.map((item) => <ParticipationCard key={item.id} participation={item} isRTL={isRTL} t={t} />)}</>}<Text style={[styles.heading, isRTL && styles.textRtl]}>{t('impact.explore')}</Text></View>} ListEmptyComponent={<EmptyState title={t('impact.emptyTitle')} copy={t('impact.emptyCopy')} />} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: '/(student)/impact/[opportunityId]', params: { opportunityId: item.id } } as any)}><Card style={styles.card}><Text style={styles.name}>{item.title}</Text><Text style={styles.copy}>{item.organization_name} · {item.mode === 'flexible_remote' ? t('impact.remote') : formatDate(item.starts_at!, locale)}</Text><Text style={styles.copy}>{t('impact.slots', { count: item.remaining_capacity })} · {item.expected_eligible_minutes} min</Text></Card></Pressable>} />;
}
function ParticipationCard({ participation, isRTL, t }: { participation: ImpactParticipation; isRTL: boolean; t: (key: string) => string }) { const display = impactParticipationDisplay(participation, t('impact.participationUnavailable'), t('impact.organizationUnavailable')); const status = <Pill color="mint" rtl={isRTL}>{t(`impact.status.${participation.status}`)}</Pill>; return <Card style={styles.history}><View><Text style={[styles.name, isRTL && styles.textRtl]}>{display.title}</Text><Text style={[styles.copy, isRTL && styles.textRtl]}>{display.organizationName}</Text></View>{display.canOpenOpportunity ? <Pressable onPress={() => router.push({ pathname: '/(student)/impact/[opportunityId]', params: { opportunityId: participation.opportunity_id, participationId: participation.id } } as any)}>{status}</Pressable> : status}</Card>; }
function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ page: { padding: 20, paddingBottom: 112, gap: 10, backgroundColor: colors.cream }, rtl: {}, textRtl: { textAlign: 'right', writingDirection: 'rtl' }, title: { fontSize: 32, fontWeight: '900', color: colors.ink }, heading: { fontSize: 21, fontWeight: '900', color: colors.ink, marginTop: 22, marginBottom: 8 }, copy: { fontSize: 14, lineHeight: 21, color: colors.muted, marginTop: 4 }, metrics: { flexDirection: 'row', alignItems: 'stretch', marginTop: 16 }, metricsRtl: { flexDirection: 'row-reverse' }, metric: { flex: 1, minWidth: 0, alignItems: 'center' }, metricDivider: { width: 1, backgroundColor: colors.border, marginVertical: 4 }, metricValue: { fontSize: 24, fontWeight: '900', color: colors.forest, textAlign: 'center' }, metricLabel: { fontSize: 12, lineHeight: 16, color: colors.muted, marginTop: 4, textAlign: 'center' }, card: { marginBottom: 10 }, history: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }, name: { fontSize: 17, fontWeight: '900', color: colors.ink } });
