import { useCallback, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';

import { AppIcon, categoryIcon } from '@/components/app-icon';
import { OfferCard } from '@/components/offer-card';
import { EmptyState, Loading, colors } from '@/components/ui';
import { color, radius, space, type } from '@/design/tokens';
import { localizedAvailability, localizedCategory, localizedOffer, useAppLocale } from '@/i18n';
import { fulfillmentLabel } from '@/lib/presentation';
import { getCampaigns, getCategories } from '@/lib/queries';
import type { CampaignCard } from '@/lib/types';

type Category = { id: string; name: string; slug: string };

export default function Discover() {
  const [campaigns, setCampaigns] = useState<CampaignCard[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [category, setCategory] = useState<string>(); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [hasError, setHasError] = useState(false);
  const { t, isRTL, locale } = useAppLocale();
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const [nextCampaigns, nextCategories] = await Promise.all([getCampaigns(category), getCategories()]); setCampaigns(nextCampaigns); setCategories((nextCategories ?? []) as Category[]); setHasError(false); } catch { setHasError(true); } finally { setLoading(false); setRefreshing(false); } }, [category, t]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (loading) return <Loading label={t('discover.loading')} />;
  const categoryItems = [{ id: '', name: t('discover.all'), slug: 'discover' }, ...categories];
  return <FlatList data={campaigns} keyExtractor={(campaign) => campaign.id} contentContainerStyle={[styles.list, isRTL && styles.rtl]} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={color.brand}/>} ListHeaderComponent={<View><View style={[styles.identity, isRTL && styles.rowRtl]}><View style={styles.symbolSlot}><View style={styles.symbolMark} /></View><Text style={[styles.brand, isRTL && styles.textRtl]}>CINSTE</Text></View><Text style={[styles.title, isRTL && styles.textRtl]}>{t('discover.title')}</Text><Text style={[styles.subtitle, isRTL && styles.textRtl]}>{t('discover.subtitle')}</Text><FlatList horizontal={!isRTL} inverted={isRTL} showsHorizontalScrollIndicator={false} data={categoryItems} keyExtractor={(item) => item.id || 'all'} contentContainerStyle={styles.filters} renderItem={({ item }) => { const selected = category === (item.id || undefined); const label = item.slug === 'discover' ? item.name : localizedCategory(item.slug, t, item.name); return <Pressable accessibilityRole="button" accessibilityState={{ selected }} accessibilityLabel={label} onPress={() => setCategory(item.id || undefined)} style={[styles.filter, selected && styles.filterSelected, isRTL && styles.filterRtl]}><AppIcon name={item.slug === 'discover' ? 'discover' : categoryIcon(item.slug)} size={17} color={selected ? color.surface : color.brand} /><Text style={[styles.filterText, selected && styles.filterTextSelected]} numberOfLines={1}>{label}</Text></Pressable>; }}/>{hasError && <Text style={[styles.error, isRTL && styles.textRtl]}>{t('error.generic')}</Text>}<Text style={[styles.sectionTitle, isRTL && styles.textRtl]}>{t('discover.kicker')}</Text></View>} ListEmptyComponent={<EmptyState title={t('discover.emptyTitle')} copy={t('discover.emptyCopy')} />} renderItem={({ item }) => { const offer = localizedOffer(item.offers, t); return <OfferCard category={localizedCategory(offer.categories.slug, t, offer.categories.name)} categorySlug={offer.categories.slug} title={offer.name} partner={offer.partners.name} availability={localizedAvailability(item.quantity_available, locale, t)} fulfillment={fulfillmentLabel(offer.fulfillment_type, t)} imageUrl={offer.image_path} rtl={isRTL} onPress={() => router.push({ pathname: '/(student)/offer/[campaignId]', params: { campaignId: item.id } })} />; }} />;
}

const styles = StyleSheet.create({ list: { paddingHorizontal: space.lg, paddingTop: space.xl, paddingBottom: 112, gap: space.md, backgroundColor: color.canvas }, rtl: { direction: 'rtl' }, rowRtl: { flexDirection: 'row-reverse' }, textRtl: { textAlign: 'right', writingDirection: 'rtl' }, identity: { flexDirection: 'row', alignItems: 'center', gap: space.xs }, symbolSlot: { width: 28, height: 28, borderRadius: 10, backgroundColor: color.brandDark, alignItems: 'center', justifyContent: 'center' }, symbolMark: { width: 8, height: 8, borderRadius: 4, backgroundColor: color.coral }, brand: { fontSize: 18, fontWeight: '900', letterSpacing: .4, color: color.ink }, title: { ...type.display, color: color.ink, marginTop: space.xl, maxWidth: 350 }, subtitle: { ...type.body, color: color.muted, marginTop: space.xs, maxWidth: 340 }, filters: { gap: space.xs, paddingVertical: space.xl, paddingRight: space.md }, filter: { minHeight: 40, paddingHorizontal: 13, borderRadius: radius.pill, borderWidth: 1, borderColor: color.line, backgroundColor: color.surface, flexDirection: 'row', alignItems: 'center', gap: 7 }, filterRtl: { flexDirection: 'row-reverse' }, filterSelected: { backgroundColor: color.brand, borderColor: color.brand }, filterText: { ...type.meta, color: color.ink, maxWidth: 148 }, filterTextSelected: { color: color.surface }, sectionTitle: { ...type.section, color: color.ink, marginBottom: space.md }, error: { ...type.meta, color: color.danger, marginBottom: space.sm } });
