import { useCallback, useState } from 'react';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';

import { Card, Loading, Pill, colors } from '@/components/ui';
import { color, space, type } from '@/design/tokens';
import { formatDate, localizedOffer, useAppLocale } from '@/i18n';
import { claimStatusLabel, fulfillmentEmoji } from '@/lib/presentation';
import { supabase } from '@/lib/supabase';
import type { ClaimStatus, FulfillmentType } from '@/lib/types';

type Item = { id: string; status: ClaimStatus; expires_at: string | null; campaigns: { offers: { localization_key: string | null; name: string; description: string; redemption_instructions: string | null; fulfillment_type: FulfillmentType; partners: { name: string } } } };
export default function MyCinste() {
  const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [hasError, setHasError] = useState(false);
  const { t, locale, isRTL } = useAppLocale();
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const { data, error } = await supabase.from('claims').select('id,status,expires_at,campaigns(offers(localization_key,name,description,redemption_instructions,fulfillment_type,partners(name)))').order('claimed_at', { ascending: false }); if (error) throw error; setItems((data || []) as unknown as Item[]); setHasError(false); } catch { setHasError(true); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load])); if (loading) return <Loading label={t('myCinste.loading')} />;
  const sections: Array<{ key: string; statuses: ClaimStatus[] }> = [{ key: 'myCinste.active', statuses: ['active'] }, { key: 'myCinste.history', statuses: ['redeemed', 'expired', 'cancelled'] }];
  const claimTone = (status: ClaimStatus) => status === 'active' || status === 'redeemed' ? 'success' : status === 'expired' ? 'warning' : 'destructive';
  return <FlatList data={sections} keyExtractor={(section) => section.key} contentContainerStyle={[styles.page, isRTL && styles.rtl]} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={color.primary}/>} ListHeaderComponent={hasError ? <Card style={styles.error}><Text style={[styles.errorText, isRTL && styles.textRtl]}>{t('error.generic')}</Text></Card> : null} renderItem={({ item: section }) => { const claims = items.filter((claim) => section.statuses.includes(claim.status)); return <View><Text style={[styles.heading, isRTL && styles.textRtl]}>{t(section.key)}</Text>{claims.length ? claims.map((claim) => { const offer = localizedOffer(claim.campaigns.offers, t); return <Pressable key={claim.id} onPress={() => router.push({ pathname: '/(student)/claim/[claimId]', params: { claimId: claim.id } })} style={({ pressed }) => pressed && styles.cardPressed}><Card style={[styles.card, isRTL && styles.rowRtl]}><Text style={styles.emoji}>{fulfillmentEmoji(offer.fulfillment_type)}</Text><View style={styles.copyColumn}><Text style={[styles.name, isRTL && styles.textRtl]}>{offer.name}</Text>{offer.partners?.name && <Text style={[styles.partner, isRTL && styles.textRtl]}>{offer.partners.name}</Text>}{claim.expires_at && claim.status === 'active' && <Text style={[styles.expiry, isRTL && styles.textRtl]}>{t('claim.expiresAt', { date: formatDate(claim.expires_at, locale) })}</Text>}</View><Pill color={claimTone(claim.status)} rtl={isRTL}>{claimStatusLabel(claim.status, t)}</Pill></Card></Pressable>; }) : <Card style={styles.emptyCard}><Text style={[styles.empty, isRTL && styles.textRtl]}>{t(section.key === 'myCinste.active' ? 'myCinste.noActive' : 'myCinste.noHistory')}</Text></Card>}</View>; }} />;
}
const styles = StyleSheet.create({ page: { padding: space.lg, paddingBottom: 120, gap: space.xl, backgroundColor: colors.cream }, rtl: {}, rowRtl: { flexDirection: 'row-reverse' }, textRtl: { textAlign: 'right', writingDirection: 'rtl' }, heading: { ...type.section, color: colors.ink, marginBottom: space.sm }, card: { flexDirection: 'row', alignItems: 'center', gap: space.sm, marginBottom: space.xs }, cardPressed: { opacity: .92, transform: [{ scale: .99 }] }, copyColumn: { flex: 1, minWidth: 0 }, emoji: { fontSize: 28 }, name: { ...type.label, color: colors.ink }, partner: { ...type.bodySmall, color: colors.muted, marginTop: 2 }, expiry: { ...type.caption, color: color.warning, marginTop: space.xs }, emptyCard: { backgroundColor: color.surfaceSubtle }, empty: { ...type.bodySmall, color: colors.muted }, error: { backgroundColor: color.dangerSoft }, errorText: { ...type.bodySmall, color: color.danger } });
